import { test, expect, type Page } from '@playwright/test';
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="800"><rect width="640" height="800" fill="#d4cbb7"/><circle cx="430" cy="230" r="70" fill="#ede4ce"/><path d="M0 700L280 160L650 740" fill="#687566"/><path d="M0 800L450 350L670 800" fill="#354d40"/><path d="M310 800L460 410L405 800" fill="#a9b3a1"/></svg>`;
const md = '# 今日的思考\n\n## 一份**清晰**的回答\n\n- 专注当下\n- 记录行动\n\n> 每天留一点安静的时间。\n\n| 方向 | 行动 |\n| --- | --- |\n| 工作 | 每天十分钟 |\n\n```js\nconst calm = true;\n```\n\n[安全链接](https://example.com)\n\n[危险链接](javascript:alert(1))\n\n<img src=x onerror=alert(1)>\n\n![远程图片](https://example.com/tracker.png)';
function posts() { return Array.from({ length: 25 }, (_, i) => ({ id: `P${i + 1}`, masterId: i % 2 ? 'M2' : 'M1', type: i % 3 ? 'article' : 'video', title: ['山间清晨，把心安放在当下', '一杯茶的时间，慢慢找回自己的节奏', '日常修习，从一件小事开始'][i % 3] + ` · ${i + 1}`, content: '走过一段安静的山路，也给自己留出一段不被打扰的时间。\n\n分享来自本地界面验收数据。', coverMediaId: i + 1, coverUrl: '/fixture/cover.svg', status: 'approved', beliefCode: 'han_buddhism', liked: true, following: i % 2 === 0, likeCount: 12, commentCount: 23, assets: i % 3 ? [{ id: 1, mediaId: i + 1, assetType: 'image', sort: 0, url: '/fixture/cover.svg' }, { id: 2, mediaId: 90, assetType: 'image', sort: 1, url: '/fixture/second.svg' }] : [{ id: 3, mediaId: i + 1, assetType: 'video', sort: 0, url: '/fixture/video.mp4', coverUrl: '/fixture/cover.svg', duration: 64 }], createTime: '2026-09-10 10:00:00' })); }
async function setup(page: Page, options: { chatFail?: boolean; chatUnread?: number; commentsFail?: boolean; delay?: boolean } = {}) {
 await page.addInitScript(() => { localStorage.setItem('h5_token', 'fixture'); localStorage.setItem('h5-auth', JSON.stringify({ state: { role: 'customer', token: 'fixture', userId: 1, displayName: '本地验收' }, version: 0 })); });
 const calls: string[] = []; let likes = 0, follows = 0, comments = 0; let rows = posts();
 await page.route('**/fixture/*.svg', route => route.fulfill({ contentType: 'image/svg+xml', body: svg }));
 await page.route('**/fixture/video.mp4', route => route.fulfill({ status: 404, body: '' }));
 await page.route('**/api/v1/**', async route => { const req = route.request(), url = new URL(req.url()), path = url.pathname, method = req.method(); calls.push(method + ' ' + url.pathname + url.search); let data: any = { list: [], total: 0 };
  if (path.endsWith('/community/feed')) { const type = url.searchParams.get('type'), following = url.searchParams.get('following') === 'true', keyword = url.searchParams.get('keyword'), p = Number(url.searchParams.get('page') || 1); if (options.delay && type === 'article') await new Promise(r => setTimeout(r, 350)); const list = rows.filter(r => (!type || r.type === type) && (!following || r.following) && (!keyword || r.title.includes(keyword))); data = { list: list.slice((p - 1) * 12, p * 12), total: list.length, page: p, size: 12 }; }
  else if (/\/community\/posts\/P\d+$/.test(path)) data = rows.find(r => path.endsWith('/' + r.id));
  else if (path.endsWith('/like')) { likes++; if (options.delay) await new Promise(r => setTimeout(r, 200)); const id = path.split('/').at(-2); rows = rows.map(p => p.id === id ? { ...p, liked: method === 'POST', likeCount: method === 'POST' ? 13 : 11 } : p); data = { liked: method === 'POST', likeCount: method === 'POST' ? 13 : 11 }; }
  else if (path.endsWith('/follow')) { follows++; data = { following: method === 'POST' }; }
  else if (path.endsWith('/comments')) { if (method === 'POST') { comments++; if (options.delay) await new Promise(r => setTimeout(r, 250)); data = { id: 'pending-1', postId: 'P2', userId: '1', content: req.postDataJSON().content, status: 'pending', createTime: '2026-09-11' }; } else { if (options.commentsFail) return route.fulfill({ status: 503, json: { message: '评论服务暂时不可用' } }); const p = Number(url.searchParams.get('page') || 1); data = { list: Array.from({ length: p === 1 ? 20 : 3 }, (_, i) => ({ id: 'C' + ((p - 1) * 20 + i), postId: 'P2', userId: '2', content: `公开评论 ${(p - 1) * 20 + i}`, status: 'approved', createTime: '2026-09-10' })), total: 23, page: p, size: 20 }; } }
  else if (/\/masters\/M\d+$/.test(path)) data = { id: path.endsWith('M1') ? 'M1' : 'M2', dharmaName: path.endsWith('M1') ? '清和法师' : '静远法师', avatar: '', rating: 4.9, templeName: '山间小院' };
  else if (path.endsWith('/chats') || path.endsWith('/bookings/chats')) { if (options.chatFail) return route.fulfill({ status: 503, json: { message: '会话服务不可用' } }); data = { list: [{ conversationId: 'conv-1', peerName: '清和法师', unreadCount: options.chatUnread, sourceType: 'consultation', canChat: true }], total: 1 }; }
  else if (path.endsWith('/chats/unread')) data = { count: options.chatUnread ?? 0 };
  else if (path.endsWith('/messages/unread-count')) data = { count: 16 };
  else if (path.endsWith('/ai/models')) data = { list: [{ id: 'deepseek-flash', name: 'DeepSeek Flash', description: '文字与图片', supportsVision: true }], defaultModel: 'deepseek-flash', stale: false };
  else if (path.endsWith('/ai/skills')) data = { list: [{ code: 'general', name: '综合问事', inputSchema: { fields: [] } }] };
  else if (path.endsWith('/ai/topics')) data = [];
  else if (path.endsWith('/ai/sessions')) data = { list: [{ id: 1, title: 'Markdown 阅读验收', skillCode: 'general', updatedAt: '2026-09-10' }], total: 1 };
  else if (path.endsWith('/ai/sessions/1/messages')) data = { list: [{ id: 1, role: 'user', content: '**用户原文保留**', status: 'completed' }, { id: 2, role: 'assistant', content: md, status: 'completed' }], total: 2 };
  else if (path.endsWith('/ai/reports/1')) data = { id: 1, skillCode: 'bazi', title: '八字命理', question: '测试', version: '1', chapters: ['今日的思考'], status: 'ready', summary: '摘要', content: md, unlocked: true, createdAt: '2026-09-10' };
  await route.fulfill({ json: { code: 0, data } });
 });
 return { calls, counts: () => ({ likes, follows, comments }) };
}
for (const width of [320, 390, 768]) test(`feed, gallery and responsive layout ${width}`, async ({ page }) => {
 await page.setViewportSize({ width, height: 900 }); await setup(page); await page.goto('/c/community'); await expect(page.locator('.community-card')).toHaveCount(12);
 await expect(page.getByRole('heading', { name: '在这里，看见另一种生活' })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
 await page.screenshot({ path: `test-results/community/screenshots/feed-${width}.png`, fullPage: true });
 await page.getByRole('link', { name: /阅读：.* · 2$/ }).click(); await expect(page.getByRole('button', { name: '放大第 1 张图片' })).toBeVisible();
 await page.getByRole('button', { name: '第 2 张', exact: true }).click(); await expect(page.locator('.community-gallery-counter')).toHaveText('2 / 2');
 await page.getByRole('button', { name: '放大第 2 张图片' }).click(); await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeHidden();
 await page.getByRole('button', { name: '查看更多评论' }).click(); await expect(page.locator('.community-comment')).toHaveCount(23);
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); await page.screenshot({ path: `test-results/community/screenshots/detail-${width}.png`, fullPage: true });
});
test('private tab does not display notification total as chat unread', async ({ page }) => { const fixture = await setup(page); await page.goto('/c/chats'); await expect(page.getByRole('tab', { name: '我的私聊', exact: true })).toBeVisible(); await expect(page.getByText('清和法师')).toBeVisible(); expect(fixture.calls.some(c => c.includes('/messages/unread-count'))).toBeFalsy(); await page.getByRole('tab', { name: '大师广场' }).click(); await expect(page.locator('.community-card')).toHaveCount(12); await page.reload(); await expect(page.getByRole('tab', { name: '大师广场' })).toHaveAttribute('aria-selected', 'true'); });
test('chat badge uses authoritative conversation unread', async ({ page }) => { const fixture = await setup(page, { chatUnread: 3 }); await page.goto('/c/chats'); await expect(page.getByRole('tab', { name: '我的私聊 3' })).toBeVisible(); expect(fixture.calls.some(c => c.includes('/chats/unread'))).toBeTruthy(); });
test('chat list failure is retryable, not an empty list', async ({ page }) => { await setup(page, { chatFail: true }); await page.goto('/c/chats'); await expect(page.getByText('会话暂未加载，请稍后重试')).toBeVisible(); await expect(page.getByRole('button', { name: '重试', exact: true })).toBeVisible(); });
test('filters, search, following and request races', async ({ page }) => { const fixture = await setup(page, { delay: true }); await page.goto('/c/community'); await expect(page.locator('.community-card')).toHaveCount(12); await page.getByRole('button', { name: '图文', exact: true }).click(); await page.getByRole('button', { name: '视频', exact: true }).click(); await expect(page.locator('.community-card')).toHaveCount(9); await page.waitForTimeout(450); await expect(page.locator('.community-cover.is-video')).toHaveCount(9); await page.getByRole('button', { name: '关注', exact: true }).click(); await expect(page.locator('.community-card')).toHaveCount(12); expect(fixture.calls.some(c => c.includes('following=true'))).toBeTruthy(); await page.getByRole('textbox', { name: '搜索广场内容' }).fill('山间清晨'); await page.getByRole('button', { name: '搜索', exact: true }).click(); await expect(page.locator('.community-card')).toHaveCount(5); await page.getByRole('button', { name: '热门', exact: true }).click(); await expect.poll(() => fixture.calls.some(c => c.includes('sort=popular'))).toBeTruthy(); });
test('guest following stays in the plaza with an explicit login action', async ({ page }) => {
 const calls: string[] = [];
 await page.route('**/api/v1/**', route => { const url = route.request().url(); calls.push(url); return route.fulfill({ json: url.includes('/live/') || url.includes('following=true') ? { code: 40101, message: '请登录' } : { code: 0, data: { list: [], total: 0 } } }); });
 await page.goto('/c/community?filter=following');
 await page.waitForLoadState('networkidle');
 await expect(page).toHaveURL(/\/c\/community\?filter=following$/);
 await expect(page.getByText('登录后查看关注动态')).toBeVisible();
 expect(calls.some(url => url.includes('following=true') || url.includes('/live/'))).toBeFalsy();
 await page.getByRole('button', { name: '去登录', exact: true }).click();
 await expect(page).toHaveURL(/\/c\/login$/);
 await expect(page.getByRole('tab', { name: '登录', exact: true })).toBeVisible();
});
test('expired community authentication clears the role before returning to login', async ({ page }) => {
 await page.addInitScript(() => { if (sessionStorage.getItem('expired-fixture')) return; sessionStorage.setItem('expired-fixture', '1'); localStorage.setItem('h5_token', 'expired'); localStorage.setItem('h5-auth', JSON.stringify({ state: { role: 'customer', token: 'expired', userId: 1 }, version: 0 })); });
 await page.route('**/api/v1/**', route => route.fulfill({ json: { code: 0, data: { list: [], total: 0 } } }));
 await page.route('**/api/v1/community/feed**', route => route.fulfill({ json: { code: 40101, message: '未登录或登录已过期' } }));
 await page.goto('/c/community?filter=following');
 await expect(page).toHaveURL(/\/c\/login$/);
 await expect(page.getByRole('tab', { name: '登录', exact: true })).toBeVisible();
 await expect(page.getByRole('button', { name: '登 录', exact: true })).toBeVisible();
});
test('like and follow initialize accurately and prevent double submissions', async ({ page }) => { const fixture = await setup(page, { delay: true }); await page.goto('/c/community/P1'); await expect(page.getByRole('button', { name: '已关注', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: '取消点赞', exact: true })).toHaveAttribute('aria-pressed', 'true'); await page.getByRole('button', { name: '取消点赞', exact: true }).dblclick({ force: true }); await expect(page.getByRole('button', { name: '点赞', exact: true })).toHaveAttribute('aria-pressed', 'false'); expect(fixture.counts().likes).toBe(1); await page.getByRole('button', { name: '已关注', exact: true }).click(); await expect(page.getByRole('button', { name: '+ 关注', exact: true })).toBeVisible(); expect(fixture.counts().follows).toBe(1); });
test('comments failures do not hide content and submitted comments stay pending', async ({ page }) => { const fixture = await setup(page, { commentsFail: true, delay: true }); await page.goto('/c/community/P2'); await expect(page.locator('.community-detail-main h1')).toContainText('一杯茶'); await expect(page.getByText('评论服务暂时不可用')).toBeVisible(); await page.getByRole('textbox', { name: '写下评论' }).fill('感谢分享，给自己一点安静的时间。'); await page.getByRole('button', { name: '发送', exact: true }).dblclick({ force: true }); await expect(page.getByText('待审核 · 仅自己可见')).toBeVisible(); expect(fixture.counts().comments).toBe(1); await expect(page.locator('.community-comments-heading h2')).toHaveText('一起聊聊 0'); });
test('video failure has a truthful fallback and never uses a video URL as an image', async ({ page }) => { await setup(page); await page.goto('/c/community?filter=video&view=video'); await expect(page.getByText('视频暂不可播放').first()).toBeVisible(); await expect(page.locator('img[src$=".mp4"]')).toHaveCount(0); await expect(page.locator('.community-video-page')).toHaveCount(9); });
for (const width of [320, 768]) test(`safe Markdown conversation and report ${width}`, async ({ page }) => { await page.setViewportSize({ width, height: 900 }); await setup(page); await page.goto('/c/ai'); await page.getByRole('button', { name: '历史问事', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: /^Markdown 阅读验收/ }).click(); await expect(page.locator('.bubble-ai .markdown-text h2')).toHaveText('今日的思考'); await expect(page.locator('.bubble-ai table')).toBeVisible(); await expect(page.locator('.bubble-ai blockquote')).toBeVisible(); await expect(page.locator('.bubble-ai pre')).toHaveText('const calm = true;\n'); await expect(page.locator('.bubble-user')).toHaveText('**用户原文保留**'); await expect(page.locator('.bubble-ai a[href^="javascript"]')).toHaveCount(0); await expect(page.locator('.bubble-ai img')).toHaveCount(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); await page.screenshot({ path: `test-results/community/screenshots/markdown-${width}.png`, fullPage: true }); await page.goto('/c/ai/reports/1'); await expect(page.locator('.ai-report-prose table')).toBeVisible(); await expect(page.locator('#report-section-0')).toHaveText('今日的思考'); });
test('master edits preserve and reorder media before submission', async ({ page }) => {
 await setup(page); await page.addInitScript(() => { localStorage.setItem('h5-auth', JSON.stringify({ state: { role: 'master', token: 'fixture', userId: 1, masterId: 1, displayName: '作者验收' }, version: 0 })); });
 let submitted: any;
 await page.route('**/api/v1/**', async route => { const path = new URL(route.request().url()).pathname;
  if (path.endsWith('/admin/masters/community/posts')) return route.fulfill({ json: { code: 0, data: { list: [{ ...posts()[1], status: 'draft' }], total: 1 } } });
  if (path.endsWith('/admin/masters/community/posts/P2') && route.request().method() === 'PUT') { submitted = route.request().postDataJSON(); return route.fulfill({ json: { code: 0, data: { ...posts()[1], ...submitted } } }); }
  if (/\/media\/\d+$/.test(path)) return route.fulfill({ json: { code: 0, data: { id: Number(path.split('/').pop()), mediaType: 'image', status: 'ready', auditStatus: 'approved', playbackUrl: '/fixture/cover.svg' } } });
  if (path.endsWith('/live/capabilities')) return route.fulfill({ json: { code: 0, data: { canStart: false } } });
  return route.fallback();
 });
 await page.goto('/m/content'); await page.getByRole('button', { name: '编辑', exact: true }).click(); await expect(page.locator('.studio-media-preview img')).toHaveCount(2); await page.getByRole('button', { name: '前移', exact: true }).nth(1).click(); await page.getByRole('button', { name: '移除', exact: true }).nth(1).click(); await page.getByRole('button', { name: '提交审核', exact: true }).click(); await expect.poll(() => submitted?.assets).toEqual([{ mediaId: 90, assetType: 'image', sort: 0 }]); expect(submitted.coverMediaId).toBe(90); expect(submitted.submit).toBe(true);
});
for (const width of [390, 1280]) test(`admin reviews actual media ${width}`, async ({ page }) => {
 await page.setViewportSize({ width, height: 900 });
 await page.addInitScript(() => { const token = 'e30.' + btoa(JSON.stringify({ userId: 1, roles: ['platform_super'], clientId: 'platform-admin', exp: 4000000000 })) + '.fixture'; localStorage.setItem('df_platform_admin_token', token); localStorage.setItem('df_platform_admin_user', JSON.stringify({ userId: 1, nickname: '验收' })); });
 await page.route('**/fixture/*.svg', route => route.fulfill({ contentType: 'image/svg+xml', body: svg }));
 let writes = 0;
 await page.route('**/api/v1/**', route => { if (route.request().method() !== 'GET') writes++; return route.fulfill({ json: { code: 0, data: { list: [{ ...posts()[1], status: 'pending' }], total: 1, page: 1, size: 20 } } }); });
 await page.goto('http://127.0.0.1:5492/audit/design'); await page.getByRole('button', { name: '查看内容', exact: true }).filter({ visible: true }).click(); await expect(page.getByRole('dialog', { name: '内容审核预览' })).toBeVisible(); await expect(page.locator('.review-media .el-image')).toHaveCount(2); await expect(page.locator('.review-body')).toContainText('走过一段安静的山路'); expect(await page.getByRole('dialog').evaluate(e => e.getBoundingClientRect().width <= innerWidth)).toBeTruthy(); await page.screenshot({ path: `test-results/community/screenshots/admin-${width}.png`, fullPage: true }); await page.getByRole('button', { name: '关闭预览', exact: true }).click(); expect(writes).toBe(0);
});
