import {test,expect,type Page} from '@playwright/test';
const now=Math.floor(Date.now()/1000);
const campaign={id:2,title:'秋日好礼 · 积分幸运转盘',kind:'wheel',prizeName:'平安香囊礼袋',image:'',description:'一份草木香，送给幸运的你。',rules:'每人每期一次，积分参与。',prizeValue:3900,budget:100000,pointsCost:10,prizeQuantity:20,capacity:200,participantCount:0,awardedCount:0,startsAt:now-3600,endsAt:now+86400,status:'published',phase:'open',version:1,drawnAt:0,poolDigest:'',announcement:'',algorithm:'crypto-rand'};
async function auth(page:Page){await page.addInitScript(()=>{localStorage.setItem('h5_token','test');localStorage.setItem('h5-auth',JSON.stringify({state:{role:'customer',token:'test',userId:1},version:0}));localStorage.setItem('askxuan-reward-demo-v1:customer:1',JSON.stringify({balance:999999,entries:[],orders:[]}))})}
for(const width of [320,390,566,768])test(`real wheel plays inside category and preserves server result ${width}`,async({page})=>{
 await auth(page);await page.setViewportSize({width,height:987});let balance=15,joins=0,mine:any=null;const outcome=width===390?'lost':'won';
 await page.route('**/api/v1/**',async r=>{const path=new URL(r.request().url()).pathname;let data:any=[];
  if(path.endsWith('/points'))data={balance};else if(path.endsWith('/campaigns'))data=[campaign];
  else if(path.endsWith('/join')){joins++;expect(r.request().postDataJSON()).toEqual({expectedPoints:10});if(!mine){balance-=10;mine={id:8,campaignId:2,code:'WX-LIVE-8',outcome,createdAt:now,title:campaign.title,pointsSpent:10}}data=mine}
  else if(path.endsWith('/campaigns/2'))data={campaign:{...campaign,participantCount:mine?1:0,awardedCount:mine&&outcome==='won'?1:0},mine,winners:mine&&outcome==='won'?[mine]:[],pointsBalance:balance};
  else if(path.endsWith('/entries'))data=mine?[mine]:[];
  await r.fulfill({json:{code:0,data}})
 });
 await page.goto('http://127.0.0.1:5386/c/rewards?tab=wheel');await expect(page.locator('.reward-wheel')).toBeVisible();await expect(page.locator('.reward-card,.reward-demo-banner,.reward-facts,.reward-ticket')).toHaveCount(0);await expect(page.locator('body')).not.toContainText('演示');await expect(page.locator('.wheel-balance')).toContainText('15');
 await expect(page.getByRole('button',{name:'10 积分转一次'})).toBeInViewport();await page.screenshot({path:`/private/tmp/points-live-wheel-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'10 积分转一次'}).click();expect(joins).toBe(0);await expect(page.getByRole('dialog',{name:'确认积分参与'})).toContainText('参与后剩余 5 积分');await page.getByRole('button',{name:'确认扣除 10 积分'}).click();
 await expect(page.locator('.reward-wheel-wrap')).toHaveClass(/spinning/);const first=await page.locator('.reward-wheel').evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(250);expect(await page.locator('.reward-wheel').evaluate(e=>getComputedStyle(e).transform)).not.toBe(first);
 await expect(page.getByRole('dialog',{name:'参与结果'})).not.toBeVisible();await expect(page.getByRole('dialog',{name:'参与结果'})).toContainText(outcome==='won'?'恭喜中奖':'本期未中奖');await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.locator('.wheel-balance')).toContainText('5');await page.reload();await expect(page.getByRole('button',{name:'查看本次结果'})).toBeEnabled();expect(joins).toBe(1);
 await page.getByRole('button',{name:'抽奖记录',exact:true}).click();await expect(page.getByRole('dialog',{name:'抽奖记录'})).toContainText('WX-LIVE-8');await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('link',{name:'我的奖品',exact:true}).click();await expect(page.getByRole('tab',{name:'我的奖品'})).toHaveAttribute('aria-selected','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('no local fallback for empty or failed catalog and legacy links redirect',async({page})=>{
 await auth(page);let fail=false,writes=0,negativeRequests=0;
 await page.route('**/api/v1/**',async r=>{const path=new URL(r.request().url()).pathname;if(r.request().method()!=='GET')writes++;if(path.includes('-9100'))negativeRequests++;await r.fulfill(fail?{status:503,json:{code:503,message:'活动暂不可用'}}:{json:{code:0,data:path.endsWith('/points')?{balance:15}:[]}})});
 await page.goto('http://127.0.0.1:5386/c/rewards/-91001');await expect(page).toHaveURL(/tab=wheel/);await expect(page.getByText('下一份惊喜，正在准备')).toBeVisible();await expect(page.locator('body')).not.toContainText('999999');await expect(page.locator('body')).not.toContainText('演示');expect(negativeRequests).toBe(0);fail=true;await page.reload();await expect(page.getByRole('button',{name:'重新加载'})).toBeVisible();await expect(page.getByRole('button',{name:/积分转一次/})).toHaveCount(0);expect(writes).toBe(0);
});
test('reduced motion honors server result without animation delay',async({page})=>{
 await auth(page);await page.emulateMedia({reducedMotion:'reduce'});let mine:any=null;
 await page.route('**/api/v1/**',async r=>{const p=new URL(r.request().url()).pathname;if(p.endsWith('/join'))mine={id:8,campaignId:2,code:'WX-RM',outcome:'lost',createdAt:now,title:campaign.title,pointsSpent:10};await r.fulfill({json:{code:0,data:p.endsWith('/points')?{balance:15}:p.endsWith('/campaigns')?[campaign]:p.endsWith('/join')?mine:{campaign,mine,winners:[],pointsBalance:mine?5:15}}})});
 await page.goto('http://127.0.0.1:5386/c/rewards?tab=wheel');await expect(page.locator('.reward-wheel')).toHaveCSS('transition-duration','0s');await page.getByRole('button',{name:'10 积分转一次'}).click();await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await expect(page.getByRole('dialog',{name:'参与结果'})).toContainText('本期未中奖',{timeout:2000});
});
test('redemption retry keeps the request key and bounds stock quantity',async({page})=>{
 await auth(page);await page.setViewportSize({width:320,height:900});const payloads:any[]=[];let orders:any[]=[],balance=15;
 await page.route('**/api/v1/**',async r=>{const p=new URL(r.request().url()).pathname;let data:any=[];
  if(p.endsWith('/points'))data={balance};if(p.endsWith('/products'))data=[{id:1,name:'积分香囊',category:'草木好礼',image:'',description:'香囊礼物',pointsPrice:2,stock:3,status:'on_sale',version:1}];if(p.endsWith('/users/addresses'))data=[{id:1,name:'测试',phone:'13800000000',province:'上海市',city:'上海市',district:'浦东新区',detail:'测试路100号',isDefault:true}];
  if(p.endsWith('/orders')&&r.request().method()==='POST'){payloads.push(r.request().postDataJSON());if(payloads.length===1){await r.fulfill({status:503,json:{code:503,message:'请求结果未确认，请重试'}});return}balance=9;orders=[{id:1,orderNo:'PT-RETRY',productName:'积分香囊',quantity:3,pointsTotal:6,status:'pending',address:'测试路100号',receiver:'测试',mobile:'13800000000',createdAt:'2026-09-10 11:00:00',carrier:'',trackingNo:''}];data=orders[0]}else if(p.endsWith('/orders'))data=orders;
  await r.fulfill({json:{code:0,data}})
 });
 await page.goto('http://127.0.0.1:5386/c/points?tab=mall');await page.getByRole('button',{name:/积分香囊/}).click();await page.getByLabel('兑换数量').fill('99');await expect(page.getByLabel('兑换数量')).toHaveValue('3');await expect(page.getByRole('dialog',{name:'兑换商品'})).toContainText('兑换后剩余 9 积分');await page.getByRole('button',{name:'确认兑换',exact:true}).click();await expect(page.getByRole('button',{name:'重试本次兑换'})).toBeEnabled();await expect(page.getByLabel('兑换数量')).toBeDisabled();await page.getByRole('button',{name:'重试本次兑换'}).click();await expect(page.getByText('6 积分 · 待发货')).toBeVisible();expect(payloads[0]).toEqual(payloads[1]);await expect(page.locator('.points-balance')).toContainText('9');await page.screenshot({path:'/private/tmp/points-live-order-320.png',fullPage:true});
});
for(const width of [320,390,768])test(`points wallet catalog ledger and rules layout ${width}`,async({page})=>{
 await auth(page);await page.setViewportSize({width,height:987});
 await page.route('**/api/v1/**',async r=>{const p=new URL(r.request().url()).pathname;await r.fulfill({json:{code:0,data:p.endsWith('/points')?{balance:15}:p.endsWith('/ledger')?[{id:1,kind:'earn',delta:25,balanceAfter:25,referenceNo:'PAY1000',createdAt:'2026-09-10 10:00:00'},{id:2,kind:'reward_wheel',delta:-10,balanceAfter:15,referenceNo:'WX2000',createdAt:'2026-09-10 11:00:00'}]:p.endsWith('/products')?[{id:1,name:'草木香囊礼袋',category:'草木好礼',description:'一份草木香',image:'',pointsPrice:20,stock:30,status:'on_sale'},{id:2,name:'日常香珠',category:'生活好物',description:'好物',image:'',pointsPrice:10,stock:0,status:'on_sale'}]:[]}})});
 await page.goto('http://127.0.0.1:5386/c/points');await page.getByRole('button',{name:/积分规则/}).click();await expect(page.getByRole('dialog',{name:'积分规则'})).toContainText('199 元得 1 积分');await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'积分规则'})).not.toBeVisible();await page.screenshot({path:`/private/tmp/points-live-ledger-${width}.png`,fullPage:true});await page.getByRole('tab',{name:'积分商城'}).click();await expect(page.getByText('还差 5 积分')).toBeVisible();await expect(page.getByText('已兑完',{exact:true})).toBeVisible();await page.screenshot({path:`/private/tmp/points-live-mall-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('last prize keeps its campaign and result when another wheel is open',async({page})=>{
 await auth(page);await page.emulateMedia({reducedMotion:'reduce'});let mine:any=null;
 await page.route('**/api/v1/**',async r=>{const p=new URL(r.request().url()).pathname;let data:any=[];const first={...campaign,phase:mine?'exhausted':'open',prizeQuantity:1,participantCount:mine?1:0,awardedCount:mine?1:0};
 if(p.endsWith('/points'))data={balance:15};else if(p.endsWith('/campaigns'))data=[first,{...campaign,id:3,title:'第二期转盘',prizeName:'第二份奖品'}];else if(p.endsWith('/join')){mine={id:8,campaignId:2,code:'WX-LAST',outcome:'won',createdAt:now,title:campaign.title,pointsSpent:10};data=mine}else if(p.endsWith('/campaigns/2'))data={campaign:first,mine,winners:mine?[mine]:[],pointsBalance:mine?5:15};else if(p.endsWith('/campaigns/3'))data={campaign:{...campaign,id:3,title:'第二期转盘',prizeName:'第二份奖品'},mine:null,winners:[],pointsBalance:5};await r.fulfill({json:{code:0,data}})
 });
 await page.goto('http://127.0.0.1:5386/c/rewards?tab=wheel');await page.getByRole('button',{name:'10 积分转一次'}).click();await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await expect(page.getByRole('dialog',{name:'参与结果'})).toContainText('平安香囊礼袋');await expect(page.getByLabel('选择转盘活动')).toHaveValue('2');await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.getByRole('button',{name:'查看本次结果'})).toBeEnabled();
});
