import {test,expect} from '@playwright/test';
test('ECS published points activities and direct wheel preserve customer balance',async({page,request})=>{
 const phone=process.env.E2E_CUSTOMER_PHONE,password=process.env.E2E_CUSTOMER_PASSWORD;if(!phone||!password)throw new Error('Explicit customer verification credentials required');
 const login=await request.post('/api/v1/auth/login',{data:{phone,password}}),body=await login.json();expect(body.code).toBe(0);const headers={Authorization:`Bearer ${body.data.accessToken}`};
 const get=async(path:string)=>{const r=await request.get('/api/v1'+path,{headers});const b=await r.json();expect(b.code).toBe(0);return b.data};const before=await get('/points');
 const catalog=await get('/marketing/rewards/campaigns');for(const id of [2,3]){const c=catalog.find((x:any)=>x.id===id);expect(c.status).toBe('published');expect(c.phase).toBe('open');expect(c.endsAt).toBe(1790183560);expect(c.description).not.toContain('示例')}
 expect((await get('/points/products')).some((x:any)=>x.name.includes('请勿兑换'))).toBe(false);
 await page.addInitScript(data=>{localStorage.setItem('h5_token',data.accessToken);localStorage.setItem('h5-auth',JSON.stringify({state:{role:'customer',token:data.accessToken,userId:data.userInfo?.userId||1},version:0}))},body.data);
 const writes:string[]=[],errors:string[]=[];page.on('request',r=>{if(r.url().includes('/api/v1/')&&r.method()!=='GET')writes.push(new URL(r.url()).pathname)});page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:390,height:987});await page.goto('/c/points');await expect(page.locator('.points-balance')).toContainText(String(before.balance));await expect(page.locator('.points-activity-entries a')).toHaveCount(2);await page.getByRole('button',{name:/积分规则/}).click();await expect(page.getByRole('dialog',{name:'积分规则'})).toContainText('199 元得 1 积分');await page.getByRole('button',{name:'知道了'}).click();await page.screenshot({path:'/private/tmp/points-live-ecs-points.png',fullPage:true});
 await page.locator('.points-activity-entries').getByRole('link',{name:/积分转盘/}).click();await expect(page.locator('.reward-wheel')).toBeVisible();await expect(page.locator('.reward-card,.reward-demo-banner')).toHaveCount(0);await expect(page.locator('body')).not.toContainText('演示');await expect(page.getByRole('heading',{name:'秋日好礼 · 平安香囊积分转盘'})).toBeVisible();
 const detail=await get('/marketing/rewards/campaigns/2');if(!detail.mine&&detail.pointsBalance>=10){await page.getByRole('button',{name:'10 积分转一次'}).click();await expect(page.getByRole('dialog',{name:'确认积分参与'})).toContainText(`参与后剩余 ${before.balance-10} 积分`);await page.getByRole('button',{name:'再想想'}).click()}
 await page.getByRole('button',{name:'活动规则',exact:true}).click();await expect(page.getByRole('dialog',{name:'活动规则'})).toContainText('20 份');await page.getByRole('button',{name:'关闭',exact:true}).click();await page.screenshot({path:'/private/tmp/points-live-ecs-wheel.png',fullPage:true});
 await page.getByRole('tab',{name:'大奖池'}).click();await expect(page.getByRole('link',{name:/天然香珠手串大奖池/})).toBeVisible();await page.getByRole('link',{name:/天然香珠手串大奖池/}).click();await expect(page.getByText('20 积分参与',{exact:false}).first()).toBeVisible();await page.screenshot({path:'/private/tmp/points-live-ecs-pool.png',fullPage:true});
 await page.goto('/c/rewards/-91001');await expect(page).toHaveURL(/tab=wheel/);await expect(page.locator('.reward-wheel')).toBeVisible();expect(writes).toEqual([]);expect(errors).toEqual([]);expect(await get('/points')).toEqual(before);
});
