import {test,expect,type Page} from '@playwright/test';
const now=Math.floor(Date.now()/1000);
const campaign={id:1,title:'秋日有礼 · 一份温暖的相逢',kind:'pool',prizeName:'东方香囊礼盒',image:'',description:'以草木香气，为日常留一份安静。\n礼盒含香囊一枚与便携礼袋。',rules:'每人每期消耗 10 积分参与一次。平台承担奖品与中国大陆地区配送费用。中奖后请填写完整地址。',prizeValue:12800,budget:18000,pointsCost:10,prizeQuantity:1,capacity:100,participantCount:99,awardedCount:0,startsAt:now-3600,endsAt:now+3600,status:'published',phase:'open',version:1,drawnAt:0,poolDigest:'',announcement:'',algorithm:'crypto-rand-uniform-v1'};
async function auth(page:Page,role='customer'){await page.addInitScript(role=>{localStorage.setItem('h5_token','test');localStorage.setItem('h5-auth',JSON.stringify({state:{role,token:'test',userId:1,displayName:'验收用户'},version:0}));},role)}
for(const width of [375,768])test(`H5 pool record claim delivery ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await auth(page);let c={...campaign};let mine:any=null;let order:any=null;let joins=0;let claimed:any;
 await page.route('**/api/v1/**',async route=>{const r=route.request(),p=new URL(r.url()).pathname;let data:any=[];
  if(p.endsWith('/campaigns/1/join')){expect(r.postDataJSON()).toEqual({expectedPoints:10});joins++;mine={id:1,campaignId:1,code:'WX00000001-000100',outcome:'pending',createdAt:now,title:c.title,pointsSpent:10};c.participantCount=100;c.phase='full';data=mine}
  else if(p.endsWith('/campaigns/1'))data={campaign:c,mine,pointsBalance:mine?90:100,winners:mine?.outcome==='won'?[mine]:[]};else if(p.endsWith('/campaigns'))data=[c];else if(p.endsWith('/entries'))data=mine?[mine]:[];
  else if(p.endsWith('/orders/1/claim')){claimed=r.postDataJSON();order={...order,...claimed,status:'pending',claimedAt:now};data={success:true}}
  else if(p.endsWith('/orders/1/complete')){order.status='completed';order.completedAt=now;data={success:true}}
  else if(p.endsWith('/orders'))data=order?[order]:[];else if(p.endsWith('/users/addresses'))data=[{id:1,name:'验收用户',phone:'13800000000',province:'上海市',city:'上海市',district:'浦东新区',detail:'测试路 100 号',isDefault:true}];
  await route.fulfill({json:{code:0,message:'ok',data}})
 });
 await page.goto('http://127.0.0.1:5386/c/rewards');await expect(page.getByText('把小欢喜')).toBeVisible();await expect(page.getByRole('tab',{name:'大奖池'})).toBeVisible();await page.screenshot({path:`/private/tmp/askxuan-rewards-list-${width}.png`,fullPage:true,animations:'disabled'});await page.getByRole('link',{name:/秋日有礼/}).click();await expect(page.getByRole('button',{name:'10 积分参与奖池'})).toBeVisible();await page.getByRole('button',{name:'10 积分参与奖池'}).click();expect(joins).toBe(0);await expect(page.getByRole('dialog',{name:'确认积分参与'})).toBeVisible();await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.getByRole('button',{name:'已参与',exact:true})).toBeDisabled();expect(joins).toBe(1);await expect(page.getByText('1.00%',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'已参与',exact:true})).toBeDisabled();expect(joins).toBe(1);
 mine.outcome='won';c={...c,status:'drawn',phase:'drawn',awardedCount:1,drawnAt:now,poolDigest:'a'.repeat(64),announcement:'100 人参与，1 人中奖。'};order={id:1,campaignId:1,entryId:1,prizeName:c.prizeName,code:mine.code,status:'awaiting_address',receiver:'',mobile:'',address:'',carrier:'',trackingNo:'',createdAt:now,claimedAt:0,shippedAt:0,completedAt:0};await page.reload();await page.getByText('查看开奖留档信息').click();await expect(page.getByText('a'.repeat(64),{exact:true})).toBeVisible();await page.screenshot({path:`/private/tmp/askxuan-rewards-detail-${width}.png`,fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'查看奖品与领奖'}).click();await page.getByRole('button',{name:'填写收货地址'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await page.getByLabel('选择已有地址').selectOption('1');await expect(page.getByLabel('收货人',{exact:true})).toHaveValue('验收用户');await page.screenshot({path:`/private/tmp/askxuan-rewards-claim-${width}.png`,fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'确认地址，等待发货'}).click();await expect(dialog).not.toBeVisible();expect(claimed.address).toContain('测试路');await expect(page.getByText('待发货',{exact:true}).first()).toBeVisible();order.status='shipped';order.carrier='顺丰';order.trackingNo='SF-TEST-100';order.shippedAt=now;await page.getByRole('tab',{name:'参与记录'}).click();await page.getByRole('tab',{name:'我的奖品'}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'确认收货'}).click();await expect(page.getByText('已完成',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('wheel persists immediate result and shows disclosed odds',async({page})=>{await page.setViewportSize({width:390,height:844});await auth(page);let mine:any=null;let joins=0;await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname;let data:any={pointsBalance:mine?90:100,campaign:{...campaign,id:2,kind:'wheel',participantCount:mine?1:0,awardedCount:mine?1:0},mine,winners:mine?[mine]:[]};if(p.endsWith('/join')){joins++;mine={id:2,campaignId:2,code:'WX00000002-000001',outcome:'won',createdAt:now,title:'转盘测试',pointsSpent:10};data=mine}await route.fulfill({json:{code:0,message:'ok',data}})});await page.goto('http://127.0.0.1:5386/c/rewards/2');await expect(page.locator('.reward-facts')).toHaveCount(0);await page.getByRole('button',{name:'活动规则',exact:true}).click();await expect(page.getByText('下一位即时概率')).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'10 积分转一次'}).click();expect(joins).toBe(0);await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.getByRole('button',{name:'查看本次结果'})).toBeVisible();await page.getByRole('button',{name:'抽奖记录',exact:true}).click();await expect(page.getByRole('dialog',{name:'抽奖记录'})).toContainText('WX00000002-000001');await page.getByRole('button',{name:'关闭',exact:true}).click();await page.screenshot({path:'/private/tmp/askxuan-rewards-wheel.png',fullPage:true,animations:'disabled'});await page.reload();await expect(page.getByRole('button',{name:'查看本次结果',exact:true})).toBeEnabled();expect(joins).toBe(1)});
test('H5 header search only home and sign out only profile',async({page})=>{await auth(page);await page.route('**/api/v1/**',r=>r.fulfill({json:{code:0,message:'ok',data:{list:[],total:0,balance:0}}}));for(const p of ['/c','/c/','/c/chats','/c/ai','/c/shop','/c/profile','/c/points','/c/rewards']){await page.goto(`http://127.0.0.1:5386${p}`);await expect(page.locator('header').getByRole('button',{name:/退出/})).toHaveCount(0);await expect(page.locator('header').getByRole('link',{name:'搜索',exact:true})).toHaveCount(p==='/c'||p==='/c/'?1:0)}await page.goto('http://127.0.0.1:5386/c/profile');await expect(page.getByRole('button',{name:'退出登录',exact:true})).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'退出登录',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('h5_token'))).toBeNull()});
test('master profile retains exit after removing global header button',async({page})=>{await auth(page,'master');await page.route('**/api/v1/**',r=>r.fulfill({json:{code:0,message:'ok',data:{list:[],total:0,dharmaName:'测试法师',authStatus:'approved'}}}));await page.goto('http://127.0.0.1:5386/m/profile');await expect(page.locator('header').getByRole('button',{name:/退出/})).toHaveCount(0);await expect(page.getByRole('button',{name:'退出登录',exact:true})).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'退出登录',exact:true}).click();await expect(page).toHaveURL(/\/m\/login/)});
test('platform draft budget validation publish audit and ship',async({page})=>{
 const token='e30.'+Buffer.from(JSON.stringify({roles:['platform_super'],clientId:'platform-admin'})).toString('base64url')+'.test';await page.addInitScript(t=>localStorage.setItem('df_platform_admin_token',t),token);let saved:any,published=false,shipment:any;await page.route('**/api/v1/**',async route=>{const r=route.request(),p=new URL(r.url()).pathname;let data:any={};if(p.endsWith('/campaigns')&&r.method()==='POST'){saved=r.postDataJSON();data={...saved,id:3}}else if(p.endsWith('/campaigns'))data=[{...campaign,status:published?'published':'draft',phase:published?'open':'draft'}];else if(p.endsWith('/publish')){published=true;data={success:true}}else if(p.endsWith('/audit'))data=[{id:1,actor:'admin',action:'publish',detail:'规则冻结，10 积分参与',createdAt:now}];else if(p.endsWith('/campaigns/1'))data={campaign,winners:[]};else if(p.endsWith('/orders/1/ship')){shipment=r.postDataJSON();data={success:true}}else if(p.endsWith('/orders'))data=[{id:1,prizeName:campaign.prizeName,code:'WX00000001-000001',status:'pending',receiver:'验收用户',mobile:'13800000000',address:'上海测试地址',carrier:'',trackingNo:'',shippedAt:0}];await route.fulfill({json:{code:0,message:'ok',data}})});
 await page.goto('http://127.0.0.1:5387/marketing/rewards');await page.getByRole('button',{name:'创建积分活动'}).click();let d=page.getByRole('dialog');await expect(d).toBeVisible();await d.getByRole('textbox').nth(0).fill('平台好礼测试');await d.getByRole('textbox').nth(1).fill('香囊礼盒');await d.locator('textarea').nth(0).fill('平台预算奖品详情');await expect(d.getByRole('button',{name:'保存草稿'})).toBeInViewport();await page.screenshot({path:'/private/tmp/askxuan-rewards-admin-create.png',fullPage:true,animations:'disabled'});await d.getByRole('button',{name:'保存草稿'}).click();await expect(d).not.toBeVisible();expect(saved.budget).toBe(15000);expect(saved.pointsCost).toBe(10);expect(saved.prizeValue).toBe(10000);expect(saved.endsAt).toBeGreaterThan(saved.startsAt);
 await page.getByRole('button',{name:'发布',exact:true}).click();await page.getByRole('button',{name:'确认发布',exact:true}).click();await expect.poll(()=>published).toBe(true);await page.getByRole('button',{name:'详情 / 审计'}).click();d=page.getByRole('dialog');await expect(d.getByRole('heading',{name:'操作留档',exact:true})).toBeVisible();await d.getByRole('button',{name:/关闭此对话框|Close this dialog/}).click();await page.getByRole('tab',{name:'奖品履约'}).click();await page.getByRole('button',{name:'登记发货'}).click();d=page.getByRole('dialog');await d.getByRole('textbox').nth(0).fill('顺丰');await d.getByRole('textbox').nth(1).fill('SF100000');await d.getByRole('button',{name:'确认发货'}).click();await expect(d).not.toBeVisible();expect(shipment).toEqual({carrier:'顺丰',trackingNo:'SF100000'});await page.screenshot({path:'/private/tmp/askxuan-rewards-admin-orders.png',fullPage:true,animations:'disabled'});
});

test('points is the activity entrance and wheel tab deep links work',async({page})=>{
 await auth(page); await page.setViewportSize({width:390,height:844});
 await page.route('**/api/v1/**',async r=>{const p=new URL(r.request().url()).pathname;const data=p.endsWith('/points')?{balance:100}:p.endsWith('/campaigns')?[campaign]:p.includes('ledger')?[]:{list:[],total:0};await r.fulfill({json:{code:0,message:'ok',data}})});
 await page.goto('http://127.0.0.1:5386/c/points');await expect(page.locator('.points-activity-entries').getByRole('link',{name:/积分转盘/})).toBeVisible();await expect(page.getByRole('link',{name:/大奖池 一期一码/})).toBeVisible();await expect(page.locator('.reward-card')).toHaveCount(0);await expect(page.getByRole('heading',{name:'好礼与体验'})).toHaveCount(0);await page.screenshot({path:'/private/tmp/askxuan-points-activities.png',fullPage:true});
 await page.locator('.points-activity-entries').getByRole('link',{name:/积分转盘/}).click();await expect(page.getByRole('tab',{name:'幸运转盘'})).toHaveAttribute('aria-selected','true');
 for(const path of ['/c','/c/profile']) {await page.goto('http://127.0.0.1:5386'+path);await expect(page.locator('a[href^="/c/rewards"]')).toHaveCount(0)}
});
test('insufficient balance and cancelled confirmation never submit a join',async({page})=>{
 await auth(page);let balance=9,joins=0,phase='open';
 await page.route('**/api/v1/**',async r=>{if(r.request().method()==='POST')joins++;await r.fulfill({json:{code:0,message:'ok',data:{campaign:{...campaign,phase},mine:null,winners:[],pointsBalance:balance}}})});
 await page.goto('http://127.0.0.1:5386/c/rewards/1');await expect(page.getByRole('button',{name:'积分不足',exact:true})).toBeDisabled();expect(joins).toBe(0);
 balance=100;await page.reload();await page.getByRole('button',{name:'10 积分参与奖池'}).click();await expect(page.getByRole('dialog',{name:'确认积分参与'})).toContainText('参与后剩余 90 积分');await page.getByRole('button',{name:'再想想'}).click();expect(joins).toBe(0);await expect(page.getByRole('dialog',{name:'确认积分参与'})).not.toBeVisible();phase='exhausted';await page.reload();await expect(page.getByRole('button',{name:'奖品已抽完',exact:true})).toBeDisabled();expect(joins).toBe(0);
});

for(const width of [320,390,768])test(`single category entrances retain animated demos in the activity list ${width}`,async({page})=>{
 await auth(page);await page.setViewportSize({width,height:900});let writes=0;
 await page.route('**/api/v1/**',async r=>{if(r.request().method()!=='GET')writes++;await r.fulfill({json:{code:0,message:'ok',data:new URL(r.request().url()).pathname.endsWith('/points')?{balance:17}:[]}})});
 await page.goto('http://127.0.0.1:5386/c/points');await expect(page.locator('.points-activity-entries a')).toHaveCount(2);await expect(page.locator('.reward-card')).toHaveCount(0);await expect(page.getByRole('heading',{name:'好礼与体验'})).toHaveCount(0);
 const art=page.locator('.points-activity-entries .reward-gift-object').first();const first=await art.evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(300);expect(await art.evaluate(e=>getComputedStyle(e).transform)).not.toBe(first);
 await page.screenshot({path:`/private/tmp/askxuan-demo-points-${width}.png`,fullPage:true});
 await page.locator('.points-activity-entries').getByRole('link',{name:/大奖池/}).click();await expect(page.locator('.reward-demo-card')).toHaveCount(1);await page.locator('.reward-demo-card').filter({hasText:'天然香珠'}).click();await expect(page.getByText('先体验一份惊喜')).toBeVisible();await page.getByRole('button',{name:'20 积分参与奖池'}).click();await expect(page.getByRole('dialog',{name:'确认积分参与'})).toContainText('仅扣演示积分');await page.getByRole('button',{name:'确认扣除 20 积分'}).click();await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.locator('.reward-demo-banner')).toContainText('80');
 await page.reload();await expect(page.getByRole('button',{name:'已参与',exact:true})).toBeDisabled();await expect(page.locator('.reward-demo-banner')).toContainText('80');await page.getByRole('button',{name:'预览本期开奖'}).click();await expect(page.locator('.reward-pool-reveal')).toBeVisible();await expect(page.getByRole('dialog',{name:'参与结果'})).toContainText('恭喜中奖');await page.screenshot({path:`/private/tmp/askxuan-demo-win-${width}.png`});await page.getByRole('button',{name:'收好这份期待'}).click();await page.getByRole('button',{name:'查看奖品与领奖'}).click();await page.getByRole('button',{name:'使用演示地址领取'}).click();await page.getByRole('button',{name:'模拟发货'}).click();await page.getByRole('button',{name:'模拟确认收货'}).click();await expect(page.getByText('已完成',{exact:true})).toBeVisible();expect(writes).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('demo wheel decelerates before revealing and isolates accounts',async({page})=>{
 await auth(page);await page.setViewportSize({width:390,height:844});let writes=0;
 await page.route('**/api/v1/**',async r=>{if(r.request().method()!=='GET')writes++;await r.fulfill({json:{code:0,data:[]}})});
 await page.goto('http://127.0.0.1:5386/c/rewards/-91001');await page.getByRole('button',{name:'10 积分转一次'}).click();await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await expect(page.locator('.reward-wheel-wrap')).toHaveClass(/spinning/);const a=await page.locator('.reward-wheel').evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(400);const b=await page.locator('.reward-wheel').evaluate(e=>getComputedStyle(e).transform);expect(a).not.toBe(b);await expect(page.getByRole('dialog',{name:'参与结果'})).not.toBeVisible();await page.screenshot({path:'/private/tmp/askxuan-demo-wheel-spinning.png'});await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.locator('.wheel-balance')).toContainText('90');await page.reload();await expect(page.getByRole('button',{name:'查看本次结果',exact:true})).toBeEnabled();expect(writes).toBe(0);
 await page.addInitScript(()=>localStorage.setItem('h5-auth',JSON.stringify({state:{role:'customer',token:'test',userId:2},version:0})));await page.reload();await expect(page.locator('.wheel-balance')).toContainText('100');await expect(page.getByRole('button',{name:'10 积分转一次'})).toBeEnabled();
});
test('demo remains usable when activity API fails and honors reduced motion',async({page})=>{
 await auth(page);await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/api/v1/**',r=>r.fulfill({status:503,json:{code:503,message:'暂不可用'}}));
 await page.goto('http://127.0.0.1:5386/c/rewards?tab=wheel');await expect(page.locator('.reward-demo-card')).toHaveCount(1);await page.locator('.reward-demo-card').click();await expect(page.locator('.reward-wheel')).toHaveCSS('transition-duration','0s');await page.getByRole('button',{name:'10 积分转一次'}).click();await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await expect(page.getByRole('dialog',{name:'参与结果'})).toBeVisible();await page.getByRole('button',{name:'收好这份期待'}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'重置体验'}).click();await expect(page.getByRole('button',{name:'10 积分转一次'})).toBeEnabled();await expect(page.locator('.wheel-balance')).toContainText('100');
});

for(const width of [320,390,566,768])test(`wheel is a compact game with secondary rules and records ${width}`,async({page})=>{
 await auth(page);await page.setViewportSize({width,height:900});let writes=0;
 const mine={id:2,campaignId:2,code:'WX-FOCUS-LOST',outcome:'lost',createdAt:now,title:'幸运转盘',pointsSpent:10};
 await page.route('**/api/v1/**',async r=>{if(r.request().method()!=='GET')writes++;await r.fulfill({json:{code:0,data:{campaign:{...campaign,id:2,kind:'wheel',participantCount:1},mine,winners:[],pointsBalance:90}}})});
 await page.goto('http://127.0.0.1:5386/c/rewards/2');
 await expect(page.locator('.reward-facts,.reward-ticket,.reward-detail-page > .reward-record,.reward-cta,.reward-notice')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'查看本次结果',exact:true})).toBeInViewport();
 await page.getByRole('button',{name:'查看本次结果',exact:true}).click();await expect(page.getByRole('dialog',{name:'参与结果'})).toContainText('本期未中奖');await expect(page.getByRole('dialog',{name:'参与结果'})).not.toContainText('WX-FOCUS-LOST');await page.getByRole('button',{name:'收好这份期待'}).click();
 await page.screenshot({path:`/private/tmp/askxuan-wheel-focus-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'活动规则',exact:true}).click();await expect(page.getByRole('dialog',{name:'活动规则'})).toContainText('奖品数量');await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'抽奖记录',exact:true}).click();await expect(page.getByRole('dialog',{name:'抽奖记录'})).toContainText('WX-FOCUS-LOST');await page.getByRole('button',{name:'关闭',exact:true}).click();
 expect(writes).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
