import {test,expect} from '@playwright/test';
test('ECS demo wheel and pool animate without mutating real customer points',async({page,request})=>{
 const phone=process.env.E2E_CUSTOMER_PHONE,password=process.env.E2E_CUSTOMER_PASSWORD;
 if(!phone||!password)throw new Error('Explicit customer verification credentials required');
 const login=await request.post('/api/v1/auth/login',{data:{phone,password}}),body=await login.json();expect(body.code).toBe(0);
 const headers={Authorization:`Bearer ${body.data.accessToken}`};
 const points=async()=>{const r=await request.get('/api/v1/points',{headers});const b=await r.json();expect(b.code).toBe(0);return b.data.balance};
 const before=await points();
 await page.addInitScript(data=>{localStorage.setItem('h5_token',data.accessToken);localStorage.setItem('h5-auth',JSON.stringify({state:{role:'customer',token:data.accessToken,userId:data.userInfo?.userId||1},version:0}))},body.data);
 const mutations:string[]=[],errors:string[]=[];page.on('request',r=>{if(r.url().includes('/api/v1/')&&r.method()!=='GET')mutations.push(new URL(r.url()).pathname)});page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:390,height:844});await page.goto('/c/points');await expect(page.locator('.points-activity-entries a')).toHaveCount(2);await expect(page.locator('.reward-card')).toHaveCount(0);await expect(page.getByRole('heading',{name:'好礼与体验'})).toHaveCount(0);await page.screenshot({path:'/private/tmp/askxuan-demo-live-points.png',fullPage:true});
 await page.locator('.points-activity-entries').getByRole('link',{name:/积分转盘/}).click();await page.locator('.reward-demo-card').filter({hasText:'草木香囊'}).click();await expect(page.getByRole('button',{name:'10 积分转一次'})).toBeInViewport();await page.getByRole('button',{name:'10 积分转一次'}).click();await page.getByRole('button',{name:'确认扣除 10 积分'}).click();await expect(page.locator('.reward-wheel-wrap')).toHaveClass(/spinning/);await expect(page.locator('.reward-wheel')).toBeInViewport();const a=await page.locator('.reward-wheel').evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(350);expect(await page.locator('.reward-wheel').evaluate(e=>getComputedStyle(e).transform)).not.toBe(a);await page.screenshot({path:'/private/tmp/askxuan-demo-live-wheel.png'});await page.getByRole('button',{name:'收好这份期待'}).click();await expect(page.locator('.wheel-balance')).toContainText('90');await expect(page.locator('.reward-facts,.reward-ticket,.reward-detail-page > .reward-record,.reward-cta')).toHaveCount(0);await page.getByRole('button',{name:'抽奖记录',exact:true}).click();await expect(page.getByRole('dialog',{name:'抽奖记录'})).toContainText('DEMO-W-');await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('link',{name:'我的奖品',exact:true}).click();await expect(page.getByRole('tab',{name:'我的奖品'})).toHaveAttribute('aria-selected','true');
 await page.goto('/c/rewards/-91002');await page.getByRole('button',{name:'20 积分参与奖池'}).click();await page.getByRole('button',{name:'确认扣除 20 积分'}).click();await page.getByRole('button',{name:'收好这份期待'}).click();await page.getByRole('button',{name:'预览本期开奖'}).click();await expect(page.getByRole('dialog',{name:'参与结果'})).toContainText('恭喜中奖');await page.screenshot({path:'/private/tmp/askxuan-demo-live-result.png'});await page.getByRole('button',{name:'收好这份期待'}).click();await page.getByRole('button',{name:'查看奖品与领奖'}).click();const pool=page.locator('.reward-record').filter({hasText:'天然香珠手串'});await pool.getByRole('button',{name:'使用演示地址领取'}).click();await pool.getByRole('button',{name:'模拟发货'}).click();await pool.getByRole('button',{name:'模拟确认收货'}).click();await expect(pool.getByText('已完成',{exact:true})).toBeVisible();await page.screenshot({path:'/private/tmp/askxuan-demo-live-delivery.png',fullPage:true});expect(mutations).toEqual([]);expect(errors).toEqual([]);expect(await points()).toBe(before);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
