import {test,expect,type Page} from '@playwright/test';
const now=Math.floor(Date.now()/1000);
const campaign={id:1,title:'秋日有礼 · 一份温暖的相逢',kind:'pool',prizeName:'东方香囊礼盒',image:'',description:'以草木香气，为日常留一份安静。\n礼盒含香囊一枚与便携礼袋。',rules:'每人每期免费一次。平台承担奖品与中国大陆地区配送费用。中奖后请填写完整地址。',prizeValue:12800,budget:18000,prizeQuantity:1,capacity:100,participantCount:99,awardedCount:0,startsAt:now-3600,endsAt:now+3600,status:'published',phase:'open',version:1,drawnAt:0,poolDigest:'',announcement:'',algorithm:'crypto-rand-uniform-v1'};
async function auth(page:Page,role='customer'){await page.addInitScript(role=>{localStorage.setItem('h5_token','test');localStorage.setItem('h5-auth',JSON.stringify({state:{role,token:'test',userId:1,displayName:'验收用户'},version:0}));},role)}
for(const width of [375,768])test(`H5 pool record claim delivery ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await auth(page);let c={...campaign};let mine:any=null;let order:any=null;let joins=0;let claimed:any;
 await page.route('**/api/v1/**',async route=>{const r=route.request(),p=new URL(r.url()).pathname;let data:any=[];
  if(p.endsWith('/campaigns/1/join')){joins++;mine={id:1,campaignId:1,code:'WX00000001-000100',outcome:'pending',createdAt:now,title:c.title};c.participantCount=100;c.phase='full';data=mine}
  else if(p.endsWith('/campaigns/1'))data={campaign:c,mine,winners:mine?.outcome==='won'?[mine]:[]};else if(p.endsWith('/campaigns'))data=[c];else if(p.endsWith('/entries'))data=mine?[mine]:[];
  else if(p.endsWith('/orders/1/claim')){claimed=r.postDataJSON();order={...order,...claimed,status:'pending',claimedAt:now};data={success:true}}
  else if(p.endsWith('/orders/1/complete')){order.status='completed';order.completedAt=now;data={success:true}}
  else if(p.endsWith('/orders'))data=order?[order]:[];else if(p.endsWith('/users/addresses'))data=[{id:1,name:'验收用户',phone:'13800000000',province:'上海市',city:'上海市',district:'浦东新区',detail:'测试路 100 号',isDefault:true}];
  await route.fulfill({json:{code:0,message:'ok',data}})
 });
 await page.goto('http://127.0.0.1:5386/c/rewards');await expect(page.getByText('把小欢喜')).toBeVisible();await expect(page.getByRole('tab',{name:'大奖池'})).toBeVisible();await page.screenshot({path:`/private/tmp/askxuan-rewards-list-${width}.png`,fullPage:true,animations:'disabled'});await page.getByRole('link',{name:/秋日有礼/}).click();await expect(page.getByRole('button',{name:'免费参与，领取参与码'})).toBeVisible();await page.getByRole('button',{name:'免费参与，领取参与码'}).click();await expect(page.getByRole('button',{name:'已参与',exact:true})).toBeDisabled();expect(joins).toBe(1);await expect(page.getByText('1.00%',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'已参与',exact:true})).toBeDisabled();expect(joins).toBe(1);
 mine.outcome='won';c={...c,status:'drawn',phase:'drawn',awardedCount:1,drawnAt:now,poolDigest:'a'.repeat(64),announcement:'100 人参与，1 人中奖。'};order={id:1,campaignId:1,entryId:1,prizeName:c.prizeName,code:mine.code,status:'awaiting_address',receiver:'',mobile:'',address:'',carrier:'',trackingNo:'',createdAt:now,claimedAt:0,shippedAt:0,completedAt:0};await page.reload();await page.getByText('查看开奖留档信息').click();await expect(page.getByText('a'.repeat(64),{exact:true})).toBeVisible();await page.screenshot({path:`/private/tmp/askxuan-rewards-detail-${width}.png`,fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'查看奖品与领奖'}).click();await page.getByRole('button',{name:'填写收货地址'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await page.getByLabel('选择已有地址').selectOption('1');await expect(page.getByLabel('收货人',{exact:true})).toHaveValue('验收用户');await page.screenshot({path:`/private/tmp/askxuan-rewards-claim-${width}.png`,fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'确认地址，等待发货'}).click();await expect(dialog).not.toBeVisible();expect(claimed.address).toContain('测试路');await expect(page.getByText('待发货',{exact:true}).first()).toBeVisible();order.status='shipped';order.carrier='顺丰';order.trackingNo='SF-TEST-100';order.shippedAt=now;await page.getByRole('tab',{name:'参与记录'}).click();await page.getByRole('tab',{name:'我的奖品'}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'确认收货'}).click();await expect(page.getByText('已完成',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
test('wheel persists immediate result and shows disclosed odds',async({page})=>{await page.setViewportSize({width:390,height:844});await auth(page);let mine:any=null;let joins=0;await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname;let data:any={campaign:{...campaign,id:2,kind:'wheel',participantCount:mine?1:0,awardedCount:mine?1:0},mine,winners:mine?[mine]:[]};if(p.endsWith('/join')){joins++;mine={id:2,campaignId:2,code:'WX00000002-000001',outcome:'won',createdAt:now,title:'转盘测试'};data=mine}await route.fulfill({json:{code:0,message:'ok',data}})});await page.goto('http://127.0.0.1:5386/c/rewards/2');await expect(page.getByText('下一位即时概率')).toBeVisible();await page.getByRole('button',{name:'免费转一次'}).click();await expect(page.getByRole('button',{name:'查看奖品与领奖'})).toBeVisible();await page.screenshot({path:'/private/tmp/askxuan-rewards-wheel.png',fullPage:true,animations:'disabled'});await page.reload();await expect(page.getByRole('button',{name:'已参与',exact:true})).toBeDisabled();expect(joins).toBe(1)});
test('H5 header search only home and sign out only profile',async({page})=>{await auth(page);await page.route('**/api/v1/**',r=>r.fulfill({json:{code:0,message:'ok',data:{list:[],total:0,balance:0}}}));for(const p of ['/c','/c/','/c/chats','/c/ai','/c/shop','/c/profile','/c/points','/c/rewards']){await page.goto(`http://127.0.0.1:5386${p}`);await expect(page.locator('header').getByRole('button',{name:/退出/})).toHaveCount(0);await expect(page.locator('header').getByRole('link',{name:'搜索',exact:true})).toHaveCount(p==='/c'||p==='/c/'?1:0)}await page.goto('http://127.0.0.1:5386/c/profile');await expect(page.getByRole('button',{name:'退出登录',exact:true})).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'退出登录',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('h5_token'))).toBeNull()});
test('master profile retains exit after removing global header button',async({page})=>{await auth(page,'master');await page.route('**/api/v1/**',r=>r.fulfill({json:{code:0,message:'ok',data:{list:[],total:0,dharmaName:'测试法师',authStatus:'approved'}}}));await page.goto('http://127.0.0.1:5386/m/profile');await expect(page.locator('header').getByRole('button',{name:/退出/})).toHaveCount(0);await expect(page.getByRole('button',{name:'退出登录',exact:true})).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'退出登录',exact:true}).click();await expect(page).toHaveURL(/\/m\/login/)});
test('platform draft budget validation publish audit and ship',async({page})=>{
 const token='e30.'+Buffer.from(JSON.stringify({roles:['platform_super'],clientId:'platform-admin'})).toString('base64url')+'.test';await page.addInitScript(t=>localStorage.setItem('df_platform_admin_token',t),token);let saved:any,published=false,shipment:any;await page.route('**/api/v1/**',async route=>{const r=route.request(),p=new URL(r.url()).pathname;let data:any={};if(p.endsWith('/campaigns')&&r.method()==='POST'){saved=r.postDataJSON();data={...saved,id:3}}else if(p.endsWith('/campaigns'))data=[{...campaign,status:published?'published':'draft',phase:published?'open':'draft'}];else if(p.endsWith('/publish')){published=true;data={success:true}}else if(p.endsWith('/audit'))data=[{id:1,actor:'admin',action:'publish',detail:'规则冻结，免费参与',createdAt:now}];else if(p.endsWith('/campaigns/1'))data={campaign,winners:[]};else if(p.endsWith('/orders/1/ship')){shipment=r.postDataJSON();data={success:true}}else if(p.endsWith('/orders'))data=[{id:1,prizeName:campaign.prizeName,code:'WX00000001-000001',status:'pending',receiver:'验收用户',mobile:'13800000000',address:'上海测试地址',carrier:'',trackingNo:'',shippedAt:0}];await route.fulfill({json:{code:0,message:'ok',data}})});
 await page.goto('http://127.0.0.1:5387/marketing/rewards');await page.getByRole('button',{name:'创建免费活动'}).click();let d=page.getByRole('dialog');await expect(d).toBeVisible();await d.getByRole('textbox').nth(0).fill('平台好礼测试');await d.getByRole('textbox').nth(1).fill('香囊礼盒');await d.locator('textarea').nth(0).fill('平台预算奖品详情');await expect(d.getByRole('button',{name:'保存草稿'})).toBeInViewport();await page.screenshot({path:'/private/tmp/askxuan-rewards-admin-create.png',fullPage:true,animations:'disabled'});await d.getByRole('button',{name:'保存草稿'}).click();await expect(d).not.toBeVisible();expect(saved.budget).toBe(15000);expect(saved.prizeValue).toBe(10000);expect(saved.endsAt).toBeGreaterThan(saved.startsAt);
 await page.getByRole('button',{name:'发布',exact:true}).click();await page.getByRole('button',{name:'确认发布',exact:true}).click();await expect.poll(()=>published).toBe(true);await page.getByRole('button',{name:'详情 / 审计'}).click();d=page.getByRole('dialog');await expect(d.getByRole('heading',{name:'操作留档',exact:true})).toBeVisible();await d.getByRole('button',{name:/关闭此对话框|Close this dialog/}).click();await page.getByRole('tab',{name:'奖品履约'}).click();await page.getByRole('button',{name:'登记发货'}).click();d=page.getByRole('dialog');await d.getByRole('textbox').nth(0).fill('顺丰');await d.getByRole('textbox').nth(1).fill('SF100000');await d.getByRole('button',{name:'确认发货'}).click();await expect(d).not.toBeVisible();expect(shipment).toEqual({carrier:'顺丰',trackingNo:'SF100000'});await page.screenshot({path:'/private/tmp/askxuan-rewards-admin-orders.png',fullPage:true,animations:'disabled'});
});
