<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessageBox} from 'element-plus'
import client from '@/api/client'
const list=ref<any[]>([]),masters=ref<any[]>([]),master=ref(''),email=ref(''),username=ref(''),busy=ref(false),error=ref(''),notice=ref('')
async function load(){try{list.value=(await client.get<{list:any[]}>('/auth/onboarding/managed')).list;masters.value=(await client.get<{list:any[]}>('/auth/onboarding/managed/candidates')).list}catch(e){error.value=(e as Error).message}}
async function create(){busy.value=true;error.value='';notice.value='';try{await client.post('/auth/onboarding/managed',{masterCode:master.value,email:email.value,username:username.value});notice.value='已分配账号。请通知本人前往大师端，选择“寺院分配账号激活”，通过此邮箱验证并设置密码。';email.value='';username.value='';master.value='';await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function revoke(id:number){try{await ElMessageBox.confirm('停用后该账号不能登录，已有登录会话也将失效。大师档案和订单会保留。','停用账号');busy.value=true;await client.post('/auth/onboarding/managed/revoke',{id});await load()}catch(e){if(e!=='cancel'&&e!=='close')error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function restore(id:number){try{await ElMessageBox.confirm('恢复后，已激活账号可重新登录；未激活账号仍须本人验证邮箱并设置密码。','恢复账号');busy.value=true;await client.post('/auth/onboarding/managed/restore',{id});await load()}catch(e){if(e!=='cancel'&&e!=='close')error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="df-page"><h1>大师账号分配</h1><p>为本寺已认证的纳管大师分配账号，由本人在大师端验证邮箱并设置密码。</p><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><form class="df-card" style="padding:24px;display:grid;gap:16px;max-width:640px" @submit.prevent="create"><label>选择本寺大师<el-select v-model="master" placeholder="选择已完成认证的大师" filterable><el-option v-for="m in masters" :key="m.code" :value="m.code" :label="m.name"/></el-select></label><label>本人邮箱<el-input v-model="email" type="email" required maxlength="254"/></label><label>登录用户名<el-input v-model="username" required pattern="[a-z][a-z0-9_]{3,31}" maxlength="32" placeholder="4–32 位小写字母、数字或下划线"/></label><el-button native-type="submit" type="primary" :disabled="busy||!master">分配账号</el-button></form><el-table :data="list"><el-table-column prop="masterCode" label="大师编号"/><el-table-column prop="username" label="用户名"/><el-table-column prop="email" label="激活邮箱"/><el-table-column label="状态"><template #default="{row}">{{row.status==='pending'?'待本人激活':row.status==='activated'?'已激活':'已停用'}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status==='revoked'" :disabled="busy" @click="restore(row.id)">恢复账号</el-button><el-button v-else :disabled="busy" @click="revoke(row.id)">停用账号</el-button></template></el-table-column></el-table></div></template>
