<script setup lang="ts">
import {ref,watch,nextTick,onBeforeUnmount} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import * as echarts from 'echarts/core'
import {GraphChart} from 'echarts/charts'
import {TooltipComponent} from 'echarts/components'
import {CanvasRenderer} from 'echarts/renderers'
echarts.use([GraphChart,TooltipComponent,CanvasRenderer])
import client from '@/api/client'
const props=defineProps<{baseId:string}>()
interface Node {id:string;name:string;document:string;chunks:string[];attributes:string[];source:string}
interface Graph {engine:string;nodes:Node[];edges:{source:string;target:string;name:string}[];truncated:boolean}
const graph=ref<Graph>(),state=ref<{revision:number;summary_model_id:string;indexing_strategy:{graph_enabled:boolean}}>(),query=ref(''),error=ref(''),busy=ref(false),selected=ref<Node>(),canvas=ref<HTMLElement>(),view=ref('graph')
const models=ref<{id:string;name:string}[]>([]),model=ref(''),extractEnabled=ref(false),preview=ref(false),chunks=ref<{id:string;content:string;chunk_index:number}[]>([]),chunkPage=ref(1),chunkTotal=ref(0)
async function showSource(n:Node){selected.value=n;chunkPage.value=1;preview.value=true;await loadChunks()}
async function loadChunks(){if(!selected.value)return;try{const r=await client.get<{list:typeof chunks.value;total:number}>(`/ai/admin/knowledge-bases/${props.baseId}/documents/${selected.value.document}/chunks?page=${chunkPage.value}`);chunks.value=r.list||[];chunkTotal.value=r.total}catch(e){error.value=e instanceof Error?e.message:'原文读取失败'}}
let chart:echarts.ECharts|undefined,observer:ResizeObserver|undefined,generation=0
function dispose(){observer?.disconnect();chart?.dispose();chart=undefined}
async function draw(){await nextTick();dispose();if(!canvas.value||!graph.value?.nodes.length||view.value!=='graph')return;chart=echarts.init(canvas.value);chart.setOption({animation:false,tooltip:{renderMode:'richText'},series:[{type:'graph',layout:'force',roam:true,draggable:true,force:{repulsion:160},data:graph.value.nodes.map(n=>({id:n.id,name:n.name,symbolSize:20})),links:graph.value.edges.map(e=>({...e,value:e.name})),label:{show:graph.value.nodes.length<40,position:'bottom'},edgeLabel:{show:graph.value.nodes.length<20,formatter:'{c}'},lineStyle:{color:'#8d9f97'},itemStyle:{color:'#426d60'},emphasis:{focus:'adjacency'},edgeSymbol:['none','arrow']}]});chart.on('click',e=>{const data=e.data as {id?:string};if(e.dataType==='node')selected.value=graph.value?.nodes.find(n=>n.id===data.id)});observer=new ResizeObserver(()=>chart?.resize());observer.observe(canvas.value)}
async function load(){const request=++generation,kb=props.baseId;busy.value=true;error.value='';selected.value=undefined;graph.value=undefined;dispose();try{const s=await client.get<typeof state.value>(`/ai/admin/knowledge-bases/${kb}/wiki`);if(request!==generation)return;state.value=s;extractEnabled.value=!!s?.indexing_strategy.graph_enabled;model.value=s?.summary_model_id||model.value;models.value=await client.get<typeof models.value>(`/ai/admin/knowledge-bases/${kb}/wiki-models`);if(!model.value)model.value=models.value[0]?.id||'';const g=await client.get<Graph>(`/ai/admin/knowledge-bases/${kb}/graph?query=${encodeURIComponent(query.value)}`);if(request!==generation)return;state.value=s;graph.value=g;await draw()}catch(e){if(request===generation)error.value=e instanceof Error?e.message:'图谱服务不可用'}finally{if(request===generation)busy.value=false}}
async function toggle(){if(!state.value)return;const enabled=extractEnabled.value;try{await ElMessageBox.confirm(enabled?'启用后，新导入或重解析的文档会调用模型抽取实体。存量文档需在文档页逐项重解析并重新审核。':'停止后续实体抽取，保留已有图谱。智能体是否读取图谱由其发布配置控制。',enabled?'启用实体抽取':'停用实体抽取',{cancelButtonText:'取消'})}catch{return}busy.value=true;try{await client.put(`/ai/admin/knowledge-bases/${props.baseId}/graph`,{enabled,model:model.value,revision:state.value.revision});ElMessage.success('抽取配置已保存');await load()}catch(e){error.value=e instanceof Error?e.message:'配置失败'}finally{busy.value=false}}
watch(()=>props.baseId,()=>{query.value='';graph.value=undefined;void load()},{immediate:true});watch(view,draw);onBeforeUnmount(()=>{generation++;dispose()})
</script>
<template><section class="entity" v-loading="busy"><header><div><h3>Neo4j 实体知识图谱</h3><p>文档中抽取的概念与关系。仅展示已审核原文的实体；机器抽取的关系仍需回到原文核实。</p></div><el-button :disabled="!state" @click="toggle">保存抽取设置</el-button><el-button @click="load">刷新</el-button></header><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form><el-switch v-model="extractEnabled" active-text="启用实体抽取"/><el-select v-model="model" placeholder="实体抽取模型"><el-option v-for="m in models" :key="m.id" :value="m.id" :label="m.name"/></el-select><span>绑定模型后启用抽取；分块与现有向量保留。</span></el-form><el-form @submit.prevent="load"><el-input v-model="query" maxlength="80" placeholder="按实体名称搜索，例如：五行" clearable/><el-button native-type="submit">搜索</el-button></el-form><p>{{graph?.nodes.length??0}} 个实体 · {{graph?.edges.length??0}} 条关系 <span v-if="graph?.truncated">（达到单次显示上限，请按实体搜索）</span></p><el-radio-group v-model="view"><el-radio-button value="graph">关系图</el-radio-button><el-radio-button value="list">实体与出处</el-radio-button></el-radio-group><div v-if="view==='graph'&&graph?.nodes.length" ref="canvas" class="canvas" role="img" aria-label="实体知识图谱，列表视图可查看全部返回节点"/><el-table v-if="view==='list'" :data="graph?.nodes||[]" @row-click="(n:Node)=>selected=n"><el-table-column prop="name" label="实体"/><el-table-column prop="source" label="原文出处"/><el-table-column label="原文分块"><template #default="{row}">{{row.chunks?.length||0}}</template></el-table-column></el-table><el-empty v-if="!error&&!graph?.nodes.length" description="尚无匹配实体；请检查抽取开关、文档解析状态与原文审核状态"/><article v-if="selected"><h4>{{selected.name}}</h4><p v-for="a in selected.attributes" :key="a">{{a}}</p><p>原文出处：{{selected.source}}</p><el-button @click="showSource(selected)">查看原文分块</el-button><p>原文分块：{{selected.chunks?.join('、')}}</p></article><el-dialog v-model="preview" title="实体原文依据" width="min(780px,94vw)"><p>{{selected?.source}}</p><article v-for="c in chunks" :key="c.id"><strong>分块 {{c.chunk_index+1}} {{selected?.chunks?.includes(c.id)?'· 关联实体':''}}</strong><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{c.content}}</pre></article><el-pagination v-if="chunkTotal>20" v-model:current-page="chunkPage" :total="chunkTotal" :page-size="20" @current-change="loadChunks"/></el-dialog></section></template>
<style scoped>.entity{margin-top:24px}header{display:flex;gap:12px}header>div{flex:1}h3{margin:0}p{font-size:13px;color:var(--el-text-color-secondary);line-height:1.7;overflow-wrap:anywhere}.el-form{display:flex;gap:12px;margin:18px 0}.canvas{height:480px;margin-top:16px;border:1px solid var(--el-border-color);border-radius:12px}article{padding:16px;background:var(--el-fill-color-light)}</style>
