<script setup lang="ts">
import {onMounted,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import client from '@/api/client'
interface EngineModel {id:string;name:string;display_name:string;type:string;is_builtin:boolean;managed_by:string;status:string;parameters:{base_url:string;provider:string;embedding_parameters:{dimension:number}}}
const rows=ref<EngineModel[]>([]),busy=ref(false),error=ref(''),dialog=ref(false),editing=ref('')
const initial=()=>({name:'',displayName:'',type:'Embedding',baseUrl:'',provider:'openai',apiKey:'',dimension:512})
const form=ref(initial()),root='/ai/admin/knowledge-models'
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:'模型操作失败'}finally{busy.value=false}}
async function load(){rows.value=(await client.get<{list:EngineModel[]}>(root)).list||[]}
function edit(m?:EngineModel){editing.value=m?.id||'';form.value=m?{name:m.name,displayName:m.display_name,type:m.type,baseUrl:m.parameters.base_url,provider:m.parameters.provider,dimension:m.parameters.embedding_parameters.dimension,apiKey:''}:initial();dialog.value=true}
async function save(){await run(async()=>{if(editing.value)await client.put(root+'/'+editing.value,form.value);else await client.post(root,form.value);form.value.apiKey='';dialog.value=false;await load();ElMessage.success('模型已登记；请测试连接，再绑定知识库或智能体草稿')})}
async function test(m:EngineModel){await run(async()=>{const v=await client.post<{ok:boolean;elapsed_ms:number;observations:{dimension:number;result_count:number}}>(root+'/'+m.id+'/test',{}, {timeout:45000});ElMessage.success(`连接成功 · ${v.elapsed_ms}ms${v.observations.dimension?' · '+v.observations.dimension+' 维':''}${v.observations.result_count?' · '+v.observations.result_count+' 条重排结果':''}`)})}
async function remove(m:EngineModel){try{await ElMessageBox.confirm('仅可删除未被知识库或已发布版本引用的模型，使用中的模型需保留以便回滚。','删除模型',{type:'warning',cancelButtonText:'取消'})}catch{return}await run(async()=>{await client.delete(root+'/'+m.id);await load()})}
watch(()=>form.value.type,t=>{if(!editing.value)form.value.provider=t==='Rerank'?'generic':'openai'})
onMounted(()=>run(load))
</script>
<template><section class="ops-card" v-loading="busy"><header><div><h2>模型与连接</h2><p>Embedding 寻找资料，Rerank 筛选相关片段，KnowledgeQA 负责 Wiki 与文档理解。对话模型在智能体配置中选择。</p></div><el-button type="primary" @click="edit()">接入模型</el-button><el-button @click="run(load)">刷新</el-button></header><el-alert v-if="error" :title="error" type="error" :closable="false"/>
<el-table :data="rows"><el-table-column label="模型" min-width="220"><template #default="{row}"><strong>{{row.display_name||row.name}}</strong><small>{{row.name}} · {{row.id}}</small></template></el-table-column><el-table-column prop="type" label="用途" width="140"/><el-table-column label="维度" width="80"><template #default="{row}">{{row.type==='Embedding'?row.parameters.embedding_parameters.dimension:'—'}}</template></el-table-column><el-table-column label="管理方式" width="130"><template #default="{row}">{{row.is_builtin||row.managed_by==='yaml'?'部署预置':'管理台接入'}}</template></el-table-column><el-table-column label="操作" width="200"><template #default="{row}"><el-button link @click="test(row)">测试连接</el-button><template v-if="!row.is_builtin&&row.managed_by!=='yaml'"><el-button link @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></template></el-table-column></el-table>
<p>使用中的模型禁止改写或删除，避免已发布版本漂移。升级时新增模型：Embedding 用新知识库重新解析；Rerank 在草稿中切换并评测发布。密钥仅发送到服务器，读取接口不返回密钥。</p>
<el-dialog v-model="dialog" :title="editing?'编辑未使用的模型':'接入模型'" width="min(600px,94vw)" @closed="form.apiKey=''"><el-form label-position="top"><el-form-item label="用途"><el-select v-model="form.type" :disabled="!!editing"><el-option v-for="t in ['Embedding','Rerank','KnowledgeQA']" :key="t" :label="t" :value="t"/></el-select></el-form-item><el-form-item label="显示名称"><el-input v-model="form.displayName" maxlength="120"/></el-form-item><el-form-item label="模型名称（服务商实际标识）"><el-input v-model="form.name" maxlength="200"/></el-form-item><el-form-item label="接口协议"><el-select v-model="form.provider" :disabled="!!editing"><el-option label="OpenAI 兼容" value="openai" :disabled="form.type==='Rerank'"/><el-option label="通用 / Jina 重排格式" value="generic"/><el-option label="阿里云" value="aliyun"/></el-select></el-form-item><el-form-item label="HTTPS 接口地址"><el-input v-model="form.baseUrl" :disabled="!!editing" placeholder="https://服务域名/v1"/><small>域名须在部署出站许可范围内；普通聊天接口不能用作重排接口。</small></el-form-item><el-form-item label="API Key"><el-input v-model="form.apiKey" type="password" show-password autocomplete="new-password" :placeholder="editing?'留空保留现有密钥':'仅保存在服务器'"/></el-form-item><el-form-item v-if="form.type==='Embedding'" label="向量维度"><el-input-number v-model="form.dimension" :min="1" :max="8192"/></el-form-item></el-form><el-alert v-if="error" :title="error" type="error" :closable="false"/><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="busy" :disabled="!form.name||!form.baseUrl" @click="save">保存模型</el-button></template></el-dialog></section></template>
<style scoped>header{display:flex;align-items:flex-start;gap:12px}header>div{flex:1}h2{margin:0 0 8px}p,small{color:var(--el-text-color-secondary);font-size:13px;line-height:1.7}small{display:block;overflow-wrap:anywhere}.el-alert{margin:16px 0}</style>
