<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Collection, DocumentAdd, Upload, Refresh, Search } from '@element-plus/icons-vue'
import client from '@/api/client'
interface Base { id:string; name:string; description:string; enabled:boolean; revision:number }
interface Policy {id:string;baseId:string;source:string;enabled:boolean;revision:number}
interface Doc {id:string;title:string;file_name:string;file_type:string;parse_status:string;policy:Policy}
interface Chunk {id:string;content:string;chunk_index:number}
interface Hit {id:string;title:string;text:string;source:string;locator:string}
const root='/ai/admin/knowledge-bases'
const bases=ref<Base[]>([]),selected=ref(''),docs=ref<Doc[]>([]),total=ref(0),page=ref(1),busy=ref(false),error=ref(''),query=ref(''),hits=ref<Hit[]>([]),searched=ref(false)
const baseDialog=ref(false),baseForm=ref<Base>({id:'',name:'',description:'',enabled:false,revision:0})
const manualDialog=ref(false),manual=ref({title:'',content:'',source:''}),uploadDialog=ref(false),uploadSource=ref(''),file=ref<File|null>(null)
const preview=ref(false),previewDoc=ref<Doc|null>(null),chunks=ref<Chunk[]>([]),chunkPage=ref(1),chunkTotal=ref(0)
let timer:ReturnType<typeof setInterval>|undefined
async function run(fn:()=>Promise<void>){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:'操作失败，请重试'}finally{busy.value=false}}
async function loadBases(){const v=await client.get<{list:Base[]}>(root);bases.value=v.list||[];if(!bases.value.some(b=>b.id===selected.value))selected.value=bases.value[0]?.id||'';await loadDocs()}
async function loadDocs(){if(!selected.value){docs.value=[];total.value=0;return}const kb=selected.value;const v=await client.get<{list:Doc[];total:number}>(`${root}/${kb}/documents?page=${page.value}`);if(kb===selected.value){docs.value=v.list||[];total.value=v.total}}
async function select(){page.value=1;hits.value=[];searched.value=false;await run(loadDocs)}
function editBase(b?:Base){baseForm.value=b?{...b}:{id:'',name:'',description:'',enabled:false,revision:0};baseDialog.value=true}
async function saveBase(){await run(async()=>{const b=baseForm.value;if(b.id)await client.put(`${root}/${b.id}`,b);else{const v=await client.post<Base>(root,{name:b.name,description:b.description});selected.value=v.id}baseDialog.value=false;await loadBases()})}
async function removeBase(b:Base){try{await ElMessageBox.confirm(`将删除“${b.name}”及其全部文档、索引。历史报告仍保留引用快照。`,'删除知识库',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'})}catch{return}await run(async()=>{await client.delete(`${root}/${b.id}`);await loadBases()})}
async function saveManual(){await run(async()=>{await client.post(`${root}/${selected.value}/documents`,manual.value,{timeout:60000});manualDialog.value=false;manual.value={title:'',content:'',source:''};await loadDocs();ElMessage.success('资料已提交处理；解析完成并审核启用后才能检索')})}
function chooseFile(e:Event){file.value=(e.target as HTMLInputElement).files?.[0]||null}
async function upload(){if(!file.value)return;if(file.value.size>20*1024*1024){ElMessage.warning('文件不能超过 20MB');return}await run(async()=>{const data=new FormData();data.append('file',file.value!);data.append('source',uploadSource.value);await client.post(`${root}/${selected.value}/upload`,data,{headers:{'Content-Type':'multipart/form-data'},timeout:60000});uploadDialog.value=false;file.value=null;uploadSource.value='';await loadDocs();ElMessage.success('文件已上传，等待处理与审核')})}
async function policy(d:Doc){if(!d.policy.enabled){try{await ElMessageBox.confirm('请先预览原文分块，确认内容、来源与使用权限。启用后，绑定此库的智能体可引用这份资料。','审核启用',{confirmButtonText:'确认启用',cancelButtonText:'取消'})}catch{return}}await run(async()=>{await client.put(`${root}/${selected.value}/documents/${d.id}`,{...d.policy,enabled:!d.policy.enabled});await loadDocs()})}
async function editSource(d:Doc){try{const {value}=await ElMessageBox.prompt('填写书名、作者、版本或原始来源','编辑出处',{inputValue:d.policy.source,inputValidator:v=>Boolean(v?.trim())||'请填写出处'});await run(async()=>{await client.put(`${root}/${selected.value}/documents/${d.id}`,{...d.policy,source:value});await loadDocs()})}catch{}}
async function mutate(d:Doc,action:'delete'|'reparse'){try{await ElMessageBox.confirm(action==='delete'?'删除文档与索引，历史引用快照保留。':'文档会先退出检索，重新解析后需要再次审核启用。',action==='delete'?'删除文档':'重新解析',{type:'warning',cancelButtonText:'取消'})}catch{return}await run(async()=>{const path=`${root}/${selected.value}/documents/${d.id}`;if(action==='delete')await client.delete(path);else await client.post(path+'/reparse',{});await loadDocs()})}
async function loadChunks(){if(!previewDoc.value)return;const v=await client.get<{list:Chunk[];total:number}>(`${root}/${selected.value}/documents/${previewDoc.value.id}/chunks?page=${chunkPage.value}`);chunks.value=v.list||[];chunkTotal.value=v.total}
async function showChunks(d:Doc){previewDoc.value=d;chunkPage.value=1;chunks.value=[];preview.value=true;await run(loadChunks)}
async function search(){await run(async()=>{hits.value=[];searched.value=false;const v=await client.post<{hits:Hit[]}>(`${root}/${selected.value}/search`,{query:query.value},{timeout:60000});hits.value=v.hits;searched.value=true})}
const status=(s:string)=>({completed:'解析完成',pending:'等待处理',processing:'解析中',failed:'处理失败',deleting:'删除中'}[s]||s)
onMounted(()=>{void run(loadBases);timer=setInterval(()=>{if(!busy.value&&docs.value.some(d=>['pending','processing'].includes(d.parse_status)))void run(loadDocs)},6000)})
onUnmounted(()=>clearInterval(timer))
</script>
<template>
<section class="ops-card knowledge-library" v-loading="busy">
 <div class="ops-section-head"><div><h2><el-icon><Collection/></el-icon> 文档知识库</h2><p>WeKnora 引擎 · 原文解析、分块索引、混合检索</p></div><div><el-button :icon="Refresh" @click="run(loadBases)">刷新</el-button><el-button type="primary" @click="editBase()">新建知识库</el-button></div></div>
 <el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <div class="knowledge-layout"><aside><button v-for="b in bases" :key="b.id" type="button" class="base-item" :class="{active:selected===b.id}" @click="selected=b.id;select()"><strong>{{ b.name }}</strong><span>{{ b.enabled?'允许检索':'已停用' }}</span><small>{{ b.description||'暂无说明' }}</small></button><el-empty v-if="!bases.length" description="创建知识库后导入资料" :image-size="64"/></aside>
 <main v-if="selected"><template v-for="b in bases.filter(v=>v.id===selected)" :key="b.id"><div class="library-toolbar"><div><strong>{{ b.name }}</strong><el-tag :type="b.enabled?'success':'info'">{{ b.enabled?'已启用':'停用中' }}</el-tag></div><div><el-button text @click="editBase(b)">设置</el-button><el-button text type="danger" @click="removeBase(b)">删除库</el-button></div></div><el-alert v-if="!b.enabled" title="此知识库已停用；启用知识库和文档后，再到智能体开发中绑定并发布。" type="info" :closable="false"/></template>
 <div class="document-toolbar"><el-button :icon="Upload" type="primary" @click="uploadDialog=true">上传文档</el-button><el-button :icon="DocumentAdd" @click="manualDialog=true">添加文本</el-button><span>新资料默认待审核</span></div>
 <el-table :data="docs" empty-text="尚无文档，上传文件或添加文本开始"><el-table-column label="文档" min-width="170"><template #default="{row}"><strong>{{row.title||row.file_name}}</strong><small class="source">{{row.policy.source}}</small></template></el-table-column><el-table-column label="处理状态" width="100"><template #default="{row}">{{status(row.parse_status)}}</template></el-table-column><el-table-column label="检索" width="80"><template #default="{row}">{{row.policy.enabled?'已审核':'停用'}}</template></el-table-column><el-table-column label="管理" min-width="270"><template #default="{row}"><el-button text @click="showChunks(row)">预览</el-button><el-button text @click="editSource(row)">出处</el-button><el-button text :disabled="!row.policy.enabled&&row.parse_status!=='completed'" @click="policy(row)">{{row.policy.enabled?'停用':'审核启用'}}</el-button><el-button text @click="mutate(row,'reparse')">重解析</el-button><el-button text type="danger" @click="mutate(row,'delete')">删除</el-button></template></el-table-column></el-table>
 <el-pagination v-if="total>20" v-model:current-page="page" :page-size="20" :total="total" layout="prev,pager,next" @current-change="run(loadDocs)"/>
 <div class="retrieval"><h3>检索验证</h3><p>与 Harness 使用相同审核范围；停用库与未审核文档不会命中。</p><el-form inline @submit.prevent="search"><el-input v-model="query" placeholder="输入用户可能提出的问题" maxlength="4000" aria-label="检索问题"/><el-button :icon="Search" native-type="submit" :disabled="!query.trim()">检索</el-button></el-form><el-empty v-if="searched&&!hits.length" description="没有命中，请核对审核状态、索引和问题" :image-size="60"/><article v-for="h in hits" :key="h.id" class="knowledge-hit"><strong>{{h.title}}</strong><blockquote>{{h.text}}</blockquote><small>{{h.source}} · {{h.locator}}</small></article></div>
 </main></div>
 <el-dialog v-model="baseDialog" :title="baseForm.id?'知识库设置':'新建知识库'" width="min(560px,94vw)"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="baseForm.name" maxlength="120"/></el-form-item><el-form-item label="说明"><el-input v-model="baseForm.description" type="textarea" maxlength="1000"/></el-form-item><el-switch v-if="baseForm.id" v-model="baseForm.enabled" active-text="允许智能体检索已审核文档"/></el-form><template #footer><el-button @click="baseDialog=false">取消</el-button><el-button type="primary" :disabled="busy||!baseForm.name.trim()" @click="saveBase">保存</el-button></template></el-dialog>
 <el-dialog v-model="manualDialog" title="添加文本资料" width="min(700px,94vw)"><el-form label-position="top"><el-form-item label="标题"><el-input v-model="manual.title" maxlength="120"/></el-form-item><el-form-item label="原文 / Markdown"><el-input v-model="manual.content" type="textarea" :rows="10" maxlength="60000"/></el-form-item><el-form-item label="出处（书名、作者、版本或原始来源）"><el-input v-model="manual.source" maxlength="500"/></el-form-item></el-form><template #footer><el-button @click="manualDialog=false">取消</el-button><el-button type="primary" :disabled="busy||!manual.title.trim()||!manual.content.trim()||!manual.source.trim()" @click="saveManual">提交处理</el-button></template></el-dialog>
 <el-dialog v-model="uploadDialog" title="上传资料" width="min(560px,94vw)"><p>PDF、DOCX、XLSX、CSV、TXT、Markdown；单文件最多 20MB。扫描件效果取决于解析组件，导入后请预览核对。</p><input type="file" accept=".pdf,.docx,.xlsx,.csv,.txt,.md" @change="chooseFile"/><el-form label-position="top"><el-form-item label="出处及版本"><el-input v-model="uploadSource" maxlength="500"/></el-form-item></el-form><template #footer><el-button @click="uploadDialog=false">取消</el-button><el-button type="primary" :disabled="busy||!file||!uploadSource.trim()" @click="upload">上传并解析</el-button></template></el-dialog>
 <el-dialog v-model="preview" :title="previewDoc?.title||'原文分块'" width="min(860px,94vw)"><p>{{previewDoc?.policy.source}}</p><article v-for="c in chunks" :key="c.id" class="knowledge-hit"><small>分块 {{c.chunk_index+1}}</small><blockquote>{{c.content}}</blockquote></article><el-empty v-if="!chunks.length" description="暂无可预览分块，请等待解析完成或重新解析"/><el-pagination v-if="chunkTotal>20" v-model:current-page="chunkPage" :total="chunkTotal" :page-size="20" layout="prev,pager,next" @current-change="run(loadChunks)"/></el-dialog>
</section>
</template>
<style scoped>
.knowledge-layout{display:grid;grid-template-columns:220px minmax(0,1fr);gap:24px;margin-top:24px}.knowledge-layout aside{border-right:1px solid var(--el-border-color);padding-right:16px}.base-item{display:flex;flex-wrap:wrap;gap:8px;width:100%;text-align:left;background:transparent;border:1px solid transparent;border-radius:12px;padding:14px;margin-bottom:8px;color:inherit;cursor:pointer;transition:background-color .18s,border-color .18s}.base-item.active{border-color:var(--el-color-primary-light-7);background:var(--el-color-primary-light-9)}.base-item strong{flex:1}.base-item span,.base-item small,.source,.retrieval p,.document-toolbar span{font-size:12px;color:var(--el-text-color-secondary)}.base-item small{width:100%;line-height:1.5}.library-toolbar,.document-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.library-toolbar .el-tag{margin-left:12px}.document-toolbar{justify-content:flex-start;margin-top:18px;flex-wrap:wrap}.source{display:block;font-weight:400;margin-top:6px}.retrieval{border-top:1px solid var(--el-border-color);margin-top:24px;padding-top:12px}.retrieval .el-form{display:flex;gap:12px}.retrieval .el-input{flex:1}.knowledge-hit{border:1px solid var(--el-border-color);border-radius:12px;padding:16px;margin-top:14px}.knowledge-hit blockquote{margin:10px 0;white-space:pre-wrap;line-height:1.75;overflow-wrap:anywhere;max-height:480px;overflow:auto}.el-alert{margin-bottom:16px}.el-pagination{margin-top:16px}.el-dialog .el-form{margin-top:16px}@media(max-width:900px){.knowledge-layout{grid-template-columns:1fr}.knowledge-layout aside{border-right:0;display:flex;gap:8px;overflow:auto}.base-item{min-width:190px;width:190px}.ops-section-head{flex-wrap:wrap}}
</style>
