<script setup lang="ts">
import {ref,watch} from 'vue'
import {ElMessageBox,ElMessage} from 'element-plus'
import client from '@/api/client'
const props=defineProps<{baseId:string;slug?:string}>(),emit=defineEmits<{changed:[]}>()
interface Page {slug:string;title:string;content:string;summary:string;version:number;status:string}
interface Revision {version:number;title:string;content?:string;summary:string;edited_at:string;edit_source:string}
const dialog=ref(false),busy=ref(false),error=ref(''),history=ref<Revision[]>([]),historyTotal=ref(0),historyPage=ref(1),revision=ref<Revision>()
const blank=():Page=>({slug:'',title:'',content:'',summary:'',version:0,status:'draft'}),form=ref(blank())
const root=()=>`/ai/admin/knowledge-bases/${props.baseId}/wiki`
async function run(f:()=>Promise<void>){busy.value=true;error.value='';try{await f()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function revisions(){if(!props.slug)return;const v=await client.get<{revisions:Revision[];total:number}>(root()+`/revisions?slug=${encodeURIComponent(props.slug)}&page=${historyPage.value}`);history.value=v.revisions||[];historyTotal.value=v.total}
async function open(){dialog.value=true;form.value=blank();history.value=[];historyPage.value=1;revision.value=undefined;await run(async()=>{if(props.slug){form.value=await client.get<Page>(root()+'/page?slug='+encodeURIComponent(props.slug));await revisions()}})}
async function save(){await run(async()=>{await client.post(root()+'/'+(props.slug?'edit':'create'),{slug:form.value.slug,title:form.value.title,content:form.value.content,summary:form.value.summary,status:form.value.status,version:form.value.version});dialog.value=false;ElMessage.success('已保存 Wiki；原文检索权限不受此编辑影响');emit('changed')})}
async function inspect(v:Revision){await run(async()=>{revision.value=await client.get<Revision>(root()+`/revision?slug=${encodeURIComponent(form.value.slug)}&query=${v.version}`)})}
async function restore(){if(!revision.value)return;try{await ElMessageBox.confirm(`将版本 ${revision.value.version} 的内容恢复为一个新版本，当前内容保留在历史中。`,'恢复版本',{cancelButtonText:'取消'})}catch{return}await run(async()=>{form.value=await client.post<Page>(root()+'/revert',{slug:form.value.slug,version:form.value.version,issue:String(revision.value!.version)});revision.value=undefined;await revisions();emit('changed')})}
watch(()=>props.baseId,()=>{dialog.value=false})
</script>
<template><el-button @click="open">{{slug?'编辑与历史':'新建 Wiki 条目'}}</el-button><el-dialog v-model="dialog" :title="slug?'编辑 Wiki 条目':'新建 Wiki 条目'" width="min(960px,94vw)" :close-on-click-modal="false" append-to-body><div v-loading="busy"><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top"><el-form-item label="条目路径"><el-input v-model="form.slug" :disabled="!!slug" maxlength="200" placeholder="concept/五行"/></el-form-item><el-form-item label="标题"><el-input v-model="form.title" maxlength="200"/></el-form-item><el-form-item label="摘要"><el-input v-model="form.summary" type="textarea" :rows="2" maxlength="1000"/></el-form-item><el-form-item label="正文（Markdown；链接采用 [[条目路径]]）"><el-input v-model="form.content" type="textarea" :rows="12" maxlength="60000"/></el-form-item><el-form-item label="编辑状态"><el-select v-model="form.status"><el-option label="草稿" value="draft"/><el-option label="已发布条目" value="published"/><el-option label="归档" value="archived"/></el-select></el-form-item></el-form><p>Wiki 是人工整理与生成的辅助知识，发布条目不会绕过原文审核，也不会作为工具指令。</p><template v-if="slug"><h4>历史版本（当前 v{{form.version}}）</h4><el-table :data="history" @row-click="inspect"><el-table-column prop="version" label="版本"/><el-table-column prop="title" label="标题"/><el-table-column prop="edit_source" label="编辑来源"/><el-table-column prop="edited_at" label="时间"/></el-table><el-pagination v-if="historyTotal>20" v-model:current-page="historyPage" :total="historyTotal" :page-size="20" @current-change="run(revisions)"/><section v-if="revision"><h4>v{{revision.version}} · {{revision.title}}</h4><pre>{{revision.content}}</pre><el-button :disabled="revision.version>=form.version" @click="restore">恢复此版本</el-button></section></template></div><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="busy||!form.slug.trim()||!form.title.trim()" @click="save">保存</el-button></template></el-dialog></template>
<style scoped>pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:360px;overflow:auto}p{color:var(--el-text-color-secondary);font-size:13px}</style>
