<template>
 <div class="rewards-admin">
  <section class="rewards-banner"><div><span>PLATFORM GIFTS</span><h1>积分活动与奖品履约</h1><p>平台预算准备好礼，一人一期积分参与，开奖与履约全程留档。</p></div><el-button type="primary" size="large" @click="edit()">创建积分活动</el-button></section>
  <el-alert title="积分商城提供确定权益；转盘与大奖池扣除配置的参与积分，不收现金，不影响功德成长。奖品预算由平台承担，与参与积分分别配置。" type="info" :closable="false" show-icon />
  <el-tabs v-model="tab" @tab-change="page=1;load()"><el-tab-pane label="活动管理" name="campaigns"/><el-tab-pane label="奖品履约" name="orders"/></el-tabs>
  <div class="rewards-toolbar"><el-select v-if="tab==='campaigns'" v-model="kind" placeholder="活动类型" clearable @change="page=1;load()"><el-option label="大奖池" value="pool"/><el-option label="幸运转盘" value="wheel"/></el-select><el-select v-else v-model="status" placeholder="全部履约状态" clearable @change="page=1;load()"><el-option v-for="(v,k) in orderStates" :key="k" :value="k" :label="v"/></el-select><el-button :loading="loading" @click="load">刷新</el-button></div>
  <el-alert v-if="error" :title="error" type="error" :closable="false" />
  <el-table v-if="tab==='campaigns'" v-loading="loading" :data="campaigns" stripe>
   <el-table-column label="活动 / 期号" min-width="220"><template #default="{row}"><strong>{{row.title}}</strong><div class="muted">第 {{row.id}} 期 · {{row.kind==='pool'?'大奖池':'转盘'}} · {{row.prizeName}}</div></template></el-table-column>
   <el-table-column label="平台预算" min-width="125"><template #default="{row}">¥{{money(row.budget)}}<div class="muted">单件参考 ¥{{money(row.prizeValue)}}</div></template></el-table-column>
   <el-table-column label="参与积分" width="110"><template #default="{row}">{{row.pointsCost}} 积分</template></el-table-column>
   <el-table-column label="参与与奖品" min-width="155"><template #default="{row}">{{row.participantCount}} / {{row.capacity}} 人<div class="muted">奖品 {{row.prizeQuantity}} 份 · 已中 {{row.awardedCount}} 份</div></template></el-table-column>
   <el-table-column label="截止时间" min-width="165"><template #default="{row}">{{date(row.endsAt)}}<div class="muted">{{row.kind==='pool'?'到期自动开奖':'即转即开'}}</div></template></el-table-column>
   <el-table-column label="状态" width="140"><template #default="{row}"><el-tag :type="row.phase==='open'?'success':'info'">{{phases[row.phase]}}</el-tag></template></el-table-column>
   <el-table-column label="操作" min-width="220" fixed="right"><template #default="{row}"><el-button link type="primary" @click="inspect(row)">详情 / 审计</el-button><el-button v-if="row.status==='draft'" link type="primary" @click="edit(row)">编辑</el-button><el-button v-if="row.status==='draft'" link type="success" :disabled="busy" @click="transition(row,'publish')">发布</el-button><el-button v-if="row.phase==='awaiting_draw'" link type="warning" :disabled="busy" @click="transition(row,'draw')">补偿开奖</el-button><el-button v-if="['draft','published'].includes(row.status)&&row.participantCount===0" link type="danger" :disabled="busy" @click="transition(row,'cancel')">取消</el-button></template></el-table-column>
  </el-table>
  <el-table v-else v-loading="loading" :data="orders" stripe>
   <el-table-column label="奖品 / 中奖码" min-width="200"><template #default="{row}"><strong>{{row.prizeName}}</strong><div class="muted">{{row.code}}</div></template></el-table-column><el-table-column label="状态" width="120"><template #default="{row}"><el-tag>{{orderStates[row.status]}}</el-tag></template></el-table-column>
   <el-table-column label="收货信息" min-width="230"><template #default="{row}"><template v-if="row.address">{{row.receiver}} · {{row.mobile}}<div>{{row.address}}</div></template><span v-else class="muted">等待中奖用户提交地址</span></template></el-table-column><el-table-column label="物流" min-width="180"><template #default="{row}">{{row.carrier}} {{row.trackingNo}}<div class="muted">{{row.shippedAt?date(row.shippedAt):'尚未发货'}}</div></template></el-table-column><el-table-column label="操作" width="120" fixed="right"><template #default="{row}"><el-button v-if="row.status==='pending'" link type="primary" @click="shipping=row;carrier='';trackingNo=''">登记发货</el-button><span v-else class="muted">{{row.status==='completed'?'已完成履约':'等待下一步'}}</span></template></el-table-column>
  </el-table>
  <div class="rewards-pager"><el-button :disabled="loading||page===1" @click="page--;load()">上一页</el-button><span>第 {{page}} 页</span><el-button :disabled="loading||count<20" @click="page++;load()">下一页</el-button></div>
  <el-dialog class="rewards-dialog" v-model="editing" :title="form.id?'编辑活动草稿':'创建积分活动'" width="760px" append-to-body destroy-on-close :close-on-click-modal="false" :close-on-press-escape="!busy" :show-close="!busy">
   <el-form ref="formRef" :model="form" label-position="top" @submit.prevent="save">
    <div class="rewards-form-grid"><el-form-item label="活动标题" required><el-input v-model="form.title" maxlength="120"/></el-form-item><el-form-item label="玩法" required><el-select v-model="form.kind"><el-option value="pool" label="大奖池 · 截止后等概率开奖"/><el-option value="wheel" label="幸运转盘 · 即转即开"/></el-select></el-form-item><el-form-item label="实物奖品名称" required><el-input v-model="form.prizeName" maxlength="120"/></el-form-item><el-form-item label="奖品图片（HTTPS，可选）"><el-input v-model="form.image" placeholder="https://…"/></el-form-item>
    <el-form-item label="单件参考价值（元）" required><el-input-number v-model="prizeYuan" :min="0.01" :max="1000000" :precision="2"/></el-form-item><el-form-item label="奖品数量" required><el-input-number v-model="form.prizeQuantity" :min="1" :max="1000" :precision="0"/></el-form-item><el-form-item label="平台活动预算（元）" required><el-input-number v-model="budgetYuan" :min="0.01" :max="1000000000" :precision="2"/></el-form-item><el-form-item label="每人每期参与积分" required><el-input-number v-model="form.pointsCost" :min="1" :max="100000000" :precision="0"/></el-form-item><el-form-item label="本期参与名额" required><el-input-number v-model="form.capacity" :min="form.prizeQuantity" :max="100000" :precision="0"/></el-form-item><el-form-item label="开始时间" required><el-date-picker v-model="starts" type="datetime" placeholder="选择开始时间"/></el-form-item><el-form-item label="截止时间（必填）" required><el-date-picker v-model="ends" type="datetime" placeholder="到期结束，不等待满额"/></el-form-item></div>
    <el-alert :title="`奖品参考总值 ¥${(prizeYuan*form.prizeQuantity).toFixed(2)}；预算须覆盖奖品，建议另计包邮和履约费用。参与积分独立配置，不按商品价值自动折算。`" :type="budgetYuan>=prizeYuan*form.prizeQuantity?'info':'error'" :closable="false"/>
    <el-form-item label="奖品详情" required><el-input v-model="form.description" type="textarea" :rows="3" maxlength="10000"/></el-form-item><el-form-item label="活动规则 / 包邮范围" required><el-input v-model="form.rules" type="textarea" :rows="4" maxlength="10000"/></el-form-item><el-alert title="保存后为草稿；发布即冻结规则、时间、预算和奖品。仅无人参与时可取消。" type="warning" :closable="false"/>
   </el-form><template #footer><el-button :disabled="busy" @click="editing=false">返回</el-button><el-button type="primary" :loading="busy" @click="save">保存草稿</el-button></template>
  </el-dialog>
  <el-dialog class="rewards-dialog" :model-value="!!shipping" title="登记奖品发货" width="520px" append-to-body :close-on-click-modal="false" :close-on-press-escape="!busy" :show-close="!busy" @close="shipping=null"><template v-if="shipping"><p>{{shipping.prizeName}} · {{shipping.code}}</p><p>{{shipping.receiver}} {{shipping.mobile}}<br/>{{shipping.address}}</p><el-form label-position="top"><el-form-item label="物流公司" required><el-input v-model="carrier" maxlength="80"/></el-form-item><el-form-item label="物流单号" required><el-input v-model="trackingNo" maxlength="100"/></el-form-item></el-form></template><template #footer><el-button :disabled="busy" @click="shipping=null">取消</el-button><el-button type="primary" :loading="busy" @click="ship">确认发货</el-button></template></el-dialog>
  <el-dialog class="rewards-dialog" :model-value="!!detail" title="活动详情与操作留档" width="820px" append-to-body @close="detail=null"><template v-if="detail"><h2>{{detail.campaign.title}}</h2><el-descriptions :column="2" border><el-descriptions-item label="期号">{{detail.campaign.id}}</el-descriptions-item><el-descriptions-item label="状态">{{phases[detail.campaign.phase]}}</el-descriptions-item><el-descriptions-item label="平台预算">¥{{money(detail.campaign.budget)}}</el-descriptions-item><el-descriptions-item label="参与积分">{{detail.campaign.pointsCost}} 积分 / 期</el-descriptions-item><el-descriptions-item label="有效人数">{{detail.campaign.participantCount}}</el-descriptions-item><el-descriptions-item label="开奖时间">{{detail.campaign.drawnAt?date(detail.campaign.drawnAt):'截止后自动开奖'}}</el-descriptions-item><el-descriptions-item label="算法">{{detail.campaign.algorithm}}</el-descriptions-item></el-descriptions><p style="white-space:pre-wrap">{{detail.campaign.description}}</p><p style="white-space:pre-wrap">{{detail.campaign.rules}}</p><el-alert v-if="detail.campaign.announcement" :title="detail.campaign.announcement" :closable="false"/><p class="rewards-digest" v-if="detail.campaign.poolDigest">参与码 SHA-256：{{detail.campaign.poolDigest}}</p><h3>中奖码</h3><div class="rewards-codes"><el-tag v-for="w in detail.winners" :key="w.id">{{w.code}}</el-tag><span v-if="!detail.winners.length">暂无中奖码</span></div><h3>操作留档</h3><el-table :data="audits"><el-table-column prop="action" label="操作"/><el-table-column prop="actor" label="操作者"/><el-table-column prop="detail" label="记录" min-width="210"/><el-table-column label="时间" width="160"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column></el-table><div class="rewards-pager"><el-button :disabled="auditPage===1" @click="auditPage--;loadAudit()">上一页</el-button><span>{{auditPage}}</span><el-button :disabled="audits.length<20" @click="auditPage++;loadAudit()">下一页</el-button></div></template></el-dialog>
 </div>
</template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox,type FormInstance} from 'element-plus'
import client from '@/api/client'
interface Campaign {id:number;title:string;kind:string;prizeName:string;image:string;description:string;rules:string;prizeValue:number;budget:number;pointsCost:number;prizeQuantity:number;capacity:number;participantCount:number;awardedCount:number;startsAt:number;endsAt:number;status:string;phase:string;version:number;drawnAt:number;poolDigest:string;announcement:string;algorithm:string}
interface Order {id:number;campaignId:number;prizeName:string;code:string;status:string;receiver:string;mobile:string;address:string;carrier:string;trackingNo:string;shippedAt:number}
interface Detail {campaign:Campaign;winners:{id:number;code:string}[]}
interface Audit {id:number;actor:string;action:string;detail:string;createdAt:number}
const phases:Record<string,string>={draft:'草稿',scheduled:'未开始',open:'参与中',full:'满额待截止',awaiting_draw:'等待开奖',drawn:'已结束',cancelled:'已取消'};const orderStates:Record<string,string>={awaiting_address:'待填写地址',pending:'待发货',shipped:'已发货',completed:'已完成'}
const tab=ref('campaigns'),page=ref(1),kind=ref(''),status=ref(''),loading=ref(false),busy=ref(false),error=ref(''),campaigns=ref<Campaign[]>([]),orders=ref<Order[]>([]),editing=ref(false),formRef=ref<FormInstance>(),detail=ref<Detail|null>(null),audits=ref<Audit[]>([]),auditPage=ref(1),shipping=ref<Order|null>(null),carrier=ref(''),trackingNo=ref('');
const defaults=()=>({id:0,title:'',kind:'pool',prizeName:'',image:'',description:'',rules:'每人每期消耗页面所示积分参与一次，不收现金。参与成功后无论是否中奖均不退回积分，失败不扣分，重复请求不重复扣分。平台提供实物奖品并承担配送费用。中奖后在“我的奖品”填写收货地址。',prizeValue:10000,budget:15000,pointsCost:10,prizeQuantity:1,capacity:100,version:1});const form=reactive(defaults()),prizeYuan=ref(100),budgetYuan=ref(150),starts=ref<Date|null>(null),ends=ref<Date|null>(null);const count=computed(()=>tab.value==='campaigns'?campaigns.value.length:orders.value.length);const date=(n:number)=>new Date(n*1000).toLocaleString('zh-CN',{hour12:false});const money=(n:number)=>(n/100).toFixed(2);
async function load(){loading.value=true;error.value='';try{if(tab.value==='campaigns')campaigns.value=await client.get<Campaign[]>(`/admin/marketing/rewards/campaigns`,{params:{page:page.value,kind:kind.value}});else orders.value=await client.get<Order[]>(`/admin/marketing/rewards/orders`,{params:{page:page.value,status:status.value}})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
function edit(c?:Campaign){Object.keys(form).forEach(k=>delete (form as unknown as Record<string,unknown>)[k]);Object.assign(form,c?{id:c.id,title:c.title,kind:c.kind,prizeName:c.prizeName,image:c.image,description:c.description,rules:c.rules,prizeValue:c.prizeValue,budget:c.budget,pointsCost:c.pointsCost,prizeQuantity:c.prizeQuantity,capacity:c.capacity,version:c.version}:defaults());prizeYuan.value=form.prizeValue/100;budgetYuan.value=form.budget/100;starts.value=new Date(c?c.startsAt*1000:Date.now()+60000);ends.value=new Date(c?c.endsAt*1000:Date.now()+7*86400000);editing.value=true}
async function save(){if(!Number.isInteger(form.pointsCost)||form.pointsCost<1||!form.title.trim()||!form.prizeName.trim()||!form.description.trim()||!form.rules.trim()||!starts.value||!ends.value||ends.value.getTime()<=starts.value.getTime()||ends.value.getTime()<=Date.now()||budgetYuan.value<prizeYuan.value*form.prizeQuantity){ElMessage.error('请填写完整活动信息，预算须覆盖奖品且截止时间有效');return}busy.value=true;try{const payload={...form,prizeValue:Math.round(prizeYuan.value*100),budget:Math.round(budgetYuan.value*100),startsAt:Math.floor(starts.value.getTime()/1000),endsAt:Math.floor(ends.value.getTime()/1000)};if(form.id)await client.put(`/admin/marketing/rewards/campaigns/${form.id}`,payload);else await client.post(`/admin/marketing/rewards/campaigns`,payload);editing.value=false;ElMessage.success('草稿已保存');page.value=1;await load()}catch{}finally{busy.value=false}}
async function transition(c:Campaign,action:string){try{let payload={};if(action==='cancel'){const r=await ElMessageBox.prompt('取消后保留记录并向用户显示原因。已有参与的活动不能取消。','取消活动',{confirmButtonText:'确认取消活动',cancelButtonText:'返回',inputPlaceholder:'填写取消原因',inputValidator:v=>!!v&&v.trim().length>=2||'请填写至少两个字的原因'});payload={reason:r.value}}else await ElMessageBox.confirm(action==='publish'?'发布后参与积分、规则、预算、名额与截止时间冻结。确认平台已准备奖品和履约预算？':'将对已截止活动执行补偿开奖，已开奖活动不会重复发奖。',action==='publish'?'发布积分活动':'补偿开奖',{type:'warning',confirmButtonText:action==='publish'?'确认发布':'确认开奖',cancelButtonText:'取消'});busy.value=true;await client.post(`/admin/marketing/rewards/campaigns/${c.id}/${action}`,payload);ElMessage.success('操作完成');await load()}catch{}finally{busy.value=false}}
async function inspect(c:Campaign){try{detail.value=await client.get<Detail>(`/admin/marketing/rewards/campaigns/${c.id}`);auditPage.value=1;await loadAudit()}catch{}}
async function loadAudit(){if(!detail.value)return;try{audits.value=await client.get<Audit[]>(`/admin/marketing/rewards/campaigns/${detail.value.campaign.id}/audit`,{params:{page:auditPage.value}})}catch{audits.value=[]}}
async function ship(){if(!shipping.value)return;if(!carrier.value.trim()||trackingNo.value.trim().length<3){ElMessage.error('请填写物流公司和正确单号');return}busy.value=true;try{await client.post(`/admin/marketing/rewards/orders/${shipping.value.id}/ship`,{carrier:carrier.value.trim(),trackingNo:trackingNo.value.trim()});shipping.value=null;ElMessage.success('奖品已登记发货');await load()}catch{}finally{busy.value=false}}
onMounted(load)
</script>
<style scoped>
.rewards-banner{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:28px;border-radius:18px;background:linear-gradient(120deg,#f4ead9,#fdfaf4);border:1px solid #e6d6b9;margin-bottom:20px}.rewards-banner span{font-size:10px;letter-spacing:2px;color:#997c4c}.rewards-banner h1{font:600 25px/1.4 serif;margin:10px 0;color:#503c29}.rewards-banner p{color:#8b7560;font-size:13px;margin:0}.rewards-toolbar{display:flex;gap:12px;margin:18px 0}.rewards-toolbar .el-select{width:210px}.rewards-pager{display:flex;gap:14px;align-items:center;justify-content:center;margin:24px 0}.muted{font-size:12px;color:#948878;line-height:1.8}.rewards-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 20px}.rewards-form-grid :deep(.el-input-number),.rewards-form-grid :deep(.el-date-editor){width:100%}.rewards-codes{display:flex;flex-wrap:wrap;gap:8px}.rewards-digest{overflow-wrap:anywhere;font-size:12px;color:#8a7560}@media(max-width:640px){.rewards-banner{align-items:flex-start;flex-direction:column;padding:20px}.rewards-form-grid{grid-template-columns:1fr}}
</style>

<style>
.rewards-dialog.el-dialog{display:flex;flex-direction:column;max-width:calc(100vw - 24px);max-height:calc(100dvh - 40px);margin:20px auto!important}.rewards-dialog .el-dialog__header,.rewards-dialog .el-dialog__footer{flex-shrink:0}.rewards-dialog .el-dialog__body{overflow:auto;min-height:0}.rewards-dialog .el-form-item{margin-bottom:20px}
</style>
