<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue'
const props=defineProps<{login:(account:string,password:string,proof:{captchaId:string;captchaCode:string})=>Promise<unknown>;registerKind?:'temple'}>()
const emit=defineEmits<{success:[]}>()
const username=ref(''),agreed=ref(false),agreement=ref('')
const account=ref(''),password=ref(''),email=ref(''),code=ref(''),human=ref(''),error=ref(''),notice=ref('')
const mode=ref<'login'|'reset'|'register'>('login'),busy=ref(false),emailEnabled=ref(false),remaining=ref(0)
const captcha=ref<{id:string;image:string}>();let generation=0;let interval:ReturnType<typeof setInterval>|undefined
async function call<T>(path:string,body?:unknown):Promise<T>{const response=await fetch('/api/v1/auth/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await response.json();if(!response.ok||result.code!==0)throw new Error(result.message||'认证服务暂不可用');return result.data}
async function reload(){const id=++generation;human.value='';captcha.value=undefined;try{const result=await call<{id:string;image:string}>('captcha');if(id===generation)captcha.value=result}catch(e){if(id===generation)error.value=e instanceof Error?e.message:'验证码加载失败'}}
function proof(){if(!captcha.value||human.value.length!==5)throw new Error('请输入图片验证码');return{captchaId:captcha.value.id,captchaCode:human.value}}
async function send(){if(busy.value)return;busy.value=true;error.value='';try{const result=await call<{retryAfter:number;message:string}>('email/code',{domain:'admin',purpose:mode.value==='register'?'temple_register':'reset',email:email.value,...proof()});notice.value=result.message;remaining.value=result.retryAfter;if(interval)clearInterval(interval);interval=setInterval(()=>{remaining.value=Math.max(0,remaining.value-1)},1000)}catch(e){error.value=e instanceof Error?e.message:'发送失败'}finally{busy.value=false;void reload()}}
async function submit(){if(busy.value)return;busy.value=true;error.value='';try{if(mode.value==='login'){await props.login(account.value,password.value,proof());emit('success')}else if(mode.value==='register'){if(!agreed.value)throw new Error('请阅读并同意账号协议');const registered=await call<{accessToken:string}>('work/register',{kind:'temple',email:email.value,username:username.value,password:password.value,code:code.value,agreementVersion:agreement.value,...proof()});await call('logout',{accessToken:registered.accessToken});mode.value='login';account.value=email.value;password.value='';notice.value='账号已创建，请登录后填写寺院入驻资料'}else{await call('password/reset',{domain:'admin',email:email.value,password:password.value,code:code.value,...proof()});mode.value='login';password.value='';notice.value='密码已更新，请重新登录'}}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false;void reload()}}
function toggle(){mode.value=mode.value==='login'?'reset':'login';password.value='';error.value='';notice.value='';void reload()}
onMounted(()=>{void reload();call<{emailEnabled:boolean;agreementVersion:string}>('options').then(x=>{emailEnabled.value=x.emailEnabled;agreement.value=x.agreementVersion}).catch(()=>{})})
onBeforeUnmount(()=>{generation++;if(interval)clearInterval(interval)})
</script>
<template><form class="identity-form" @submit.prevent="submit">
<label v-if="mode==='login'">邮箱／用户名<input v-model="account" autocomplete="username" autocapitalize="none" required maxlength="254"/></label>
<label v-else>{{mode==='register'?'本人邮箱':'已验证邮箱'}}<input v-model="email" type="email" autocomplete="email" required maxlength="254"/></label>
<label v-if="mode==='register'">用户名<input v-model="username" pattern="[a-z][a-z0-9_]{3,31}" maxlength="32" required/><small>4–32 位小写字母、数字或下划线，以字母开头</small></label>
<label>{{mode==='reset'?'新密码':'密码'}}<input v-model="password" type="password" :autocomplete="mode==='login'?'current-password':'new-password'" :minlength="mode==='login'?1:12" maxlength="128" required/></label>
<label>图片验证码<span class="identity-code"><input v-model="human" aria-label="图片验证码" inputmode="numeric" maxlength="5" required/><button type="button" aria-label="更换图片验证码" :disabled="busy" @click="reload"><img v-if="captcha" :src="captcha.image" alt="五位数字验证码，点击更换"/><span v-else>重新加载</span></button></span></label>
<label v-if="mode!=='login'">邮箱验证码<span class="identity-code"><input v-model="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" required/><button type="button" :disabled="busy||remaining>0||!emailEnabled||human.length!==5" @click="send">{{remaining?`${remaining} 秒后重发`:'发送验证码'}}</button></span><small>发送后图片会更新，提交前请输入新图片验证码。新密码至少 12 个字符。</small></label>
<details v-if="mode==='register'"><summary>账号协议与隐私说明</summary><p>请使用本人邮箱注册，经办人应获得寺院授权。申请资料仅用于入驻审核，审核通过前不开放寺院业务权限；密码以哈希保存。</p></details><label v-if="mode==='register'"><span><input v-model="agreed" type="checkbox" required style="width:auto"/> 我已阅读并同意账号协议与隐私说明</span></label>
<p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><p v-if="mode!=='login'&&!emailEnabled">邮件找回暂未开放，请联系管理员。</p>
<button class="identity-primary" type="submit" :disabled="busy||!captcha||(mode!=='login'&&!emailEnabled)">{{busy?'正在处理…':mode==='login'?'登录':mode==='register'?'注册寺院入驻账号':'重置密码'}}</button>
<button type="button" :disabled="busy" @click="toggle">{{mode==='login'?'忘记密码':'返回登录'}}</button><button v-if="registerKind&&mode==='login'" type="button" :disabled="busy" @click="mode='register';error='';notice='';reload()">注册账号 · 申请寺院入驻</button><small>{{registerKind?'寺院经办人可注册并提交入驻申请，审核通过后开通管理权限。':'平台工作账户由管理员开通。'}}</small>
</form></template>
<style scoped>.identity-form{display:grid;gap:16px}.identity-form label{display:grid;gap:8px;font-size:14px}.identity-form input{min-width:0;width:100%;box-sizing:border-box;padding:12px;border:1px solid var(--color-border-default,#ccc);border-radius:8px;background:var(--color-bg-primary,#fff);color:var(--color-text-primary,#222);font-size:16px}.identity-code{display:grid;grid-template-columns:minmax(0,1fr) 140px;gap:8px}.identity-form button{min-height:44px;cursor:pointer;border:1px solid var(--color-border-default,#ccc);border-radius:8px;background:var(--color-bg-secondary,#eee);color:var(--color-text-primary,#222)}.identity-code button{padding:0;overflow:hidden}.identity-code img{display:block;width:100%;height:46px;object-fit:contain}.identity-form .identity-primary{background:var(--color-brand,#28574c);color:white}.identity-form :disabled{opacity:.5;cursor:default}.identity-form small,.identity-form [role=status]{font-size:12px;line-height:1.6}.identity-form [role=alert]{color:#bd453c}.identity-form :focus-visible{outline:2px solid var(--color-brand,#28574c);outline-offset:3px}</style>
