import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { motion } = JSON.parse(readFileSync(resolve(root, 'packages/design-tokens/tokens.json'), 'utf8'));
const css = [
  '/* Generated by scripts/sync-motion.mjs from design-tokens/tokens.json. */',
  ':root {',
  ...Object.entries(motion.duration).map(([role, value]) => `  --motion-duration-${role}: ${value}ms;`),
  `  --motion-ease: ${motion.ease};`,
  `  --motion-settle: ${motion.settle};`,
  '}',
  '/* Include pseudo-elements; keep completion events for dialogs and transitions. */',
  '@media (prefers-reduced-motion: reduce) {',
  '  *, *::before, *::after {',
  '    animation-duration: .01ms !important;',
  '    animation-delay: 0ms !important;',
  '    animation-iteration-count: 1 !important;',
  '    transition-duration: .01ms !important;',
  '    transition-delay: 0ms !important;',
  '    scroll-behavior: auto !important;',
  '  }',
  '}',
  '',
].join('\n');
let drift = false;
for (const target of ['packages/design-tokens/motion.css', 'apps/web-h5/src/theme/motion-tokens.css']) {
  if (target.startsWith('apps/web-h5') && !existsSync(resolve(root, 'apps/web-h5/src'))) continue;
  const path = resolve(root, target);
  if (process.argv.includes('--check')) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== css) { console.error('Motion drift: ' + target); drift = true; }
  } else { writeFileSync(path, css); console.log('Generated ' + target); }
}
if (drift) process.exit(1);
