<script setup lang="ts">
import {ref,computed,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import client from '@/api/client'
import PageHeader from '@/components/PageHeader.vue'
import {useAuthStore} from '@/stores/auth'
type Row=Record<string,any>
const auth=useAuthStore(),allowed=computed(()=>auth.roles.includes('platform_super'))
const modules=[{key:'orders',label:'现金订单',path:'/admin/orders'},{key:'products',label:'现金商品',path:'/admin/products'},{key:'diy',label:'DIY 订单',path:'/admin/diy/orders'},{key:'materials',label:'DIY 材料',path:'/admin/diy/materials'},{key:'points',label:'积分订单',path:'/admin/points/orders'},{key:'returns',label:'商城售后',path:'/admin/orders/returns'}]
const tab=ref('orders'),page=ref(1),rows=ref<Row[]>([]),total=ref<number|null>(null),busy=ref(false),error=ref(''),detail=ref<Row|null>(null),detailTab=ref(''),status=ref('')
const cash=ref<Row|null>(null),points=ref<Row|null>(null),diy=ref<number|null>(null),summaryErrors=ref<string[]>([])
const labels:Record<string,string>={pending_payment:'待付款',paid:'待发货',shipped:'已发货',completed:'已完成',cancelled:'已取消',in_return:'售后中',pending_review:'待审核',in_making:'制作中',awaiting_blessing:'等待加持',blessing_in_progress:'加持中',blessing_completed:'加持完成',awaiting_shipment:'待发货',pending:'待发货',draft:'草稿',on_shelf:'上架',off_shelf:'下架',on_sale:'上架',off_sale:'下架',approved:'审核通过',return_shipping:'退货运输中',return_received:'退货已收货',refunding:'退款中',rejected:'已拒绝'}
const module=computed(()=>modules.find(m=>m.key===tab.value)!)
const states=computed(()=>({orders:['pending_payment','paid','shipped','completed','in_return','cancelled'],products:['draft','on_shelf','off_shelf'],diy:['pending_review','in_making','awaiting_blessing','awaiting_shipment','shipped','completed','cancelled'],materials:['on_shelf','off_shelf'],points:['pending','shipped','completed','cancelled'],returns:['pending_review','approved','return_shipping','return_received','refunding','completed','rejected']}[tab.value]||[]))
async function load(){if(!allowed.value)return;busy.value=true;error.value='';try{const r=await client.get<any>(module.value.path,{params:{page:page.value,size:20,status:status.value||undefined}});rows.value=Array.isArray(r)?r:r.list||[];total.value=Array.isArray(r)?null:r.total}catch(e){rows.value=[];error.value=e instanceof Error?e.message:'加载失败'}finally{busy.value=false}}
async function summary(){summaryErrors.value=[];await Promise.all([client.get<Row>('/admin/orders/report').then(r=>cash.value=r).catch(()=>{cash.value=null;summaryErrors.value.push('现金经营')}),client.get<Row>('/admin/points/report').then(r=>points.value=r).catch(()=>{points.value=null;summaryErrors.value.push('积分经营')}),client.get<Row>('/admin/diy/orders',{params:{page:1,size:1}}).then(r=>diy.value=r.total).catch(()=>{diy.value=null;summaryErrors.value.push('DIY 订单')})])}
async function open(row:Row){detailTab.value=tab.value;busy.value=true;try{detail.value=tab.value==='points'?row:await client.get<Row>(`${module.value.path}/${row.id}`)}catch(e){ElMessage.error(e instanceof Error?e.message:'详情加载失败')}finally{busy.value=false}}
async function ship(){if(!detail.value)return;let carrier='',trackingNo='';try{carrier=(await ElMessageBox.prompt('填写物流公司','订单发货',{inputValidator:v=>!!v?.trim()||'请填写物流公司'})).value;trackingNo=(await ElMessageBox.prompt('填写运单号','订单发货',{inputValidator:v=>!!v?.trim()||'请填写运单号'})).value}catch{return}busy.value=true;try{const path=detailTab.value==='points'?`/admin/points/orders/${detail.value.id}/ship`:detailTab.value==='diy'?`/admin/diy/orders/${detail.value.id}/ship`:`/admin/orders/${detail.value.id}/ship`;if(detailTab.value==='points')await client.post(path,{carrier,trackingNo});else await client.put(path,{expressCompany:carrier,trackingNo});detail.value=null;ElMessage.success('发货成功');await load();await summary()}catch(e){ElMessage.error(e instanceof Error?e.message:'发货失败')}finally{busy.value=false}}
function change(){page.value=1;status.value='';void load()}
onMounted(()=>{void load();if(allowed.value)void summary()})
</script>
<template><div class="commerce-supervisor"><PageHeader title="商城运营中心" subtitle="统一查看现金商城、DIY 与积分商城，分别核算经营数据"><template #extra><el-button :loading="busy" @click="load();summary()">刷新数据</el-button></template></PageHeader>
<el-alert v-if="!allowed" title="商城经营数据仅平台超级管理员可查看" type="info" :closable="false"/>
<template v-else><section class="commerce-banner"><span>COMMERCE OVERVIEW</span><h2>从一件商品，到一次安心交付</h2><p>关注待处理订单、库存状态与售后进度，让每个环节都有回应。</p></section>
<div class="commerce-stats"><article><span>现金商城累计销售额</span><b>{{cash?'¥'+Number(cash.totalSales).toFixed(2):'—'}}</b><small>现金订单独立统计</small></article><article><span>现金订单待发货</span><b>{{cash?.pendingShip??'—'}}</b><small>优先处理已支付订单</small></article><article><span>DIY 订单</span><b>{{diy??'—'}}</b><small>定制制作履约</small></article><article><span>积分兑换待发货</span><b>{{points?.pendingCount??'—'}}</b><small>兑换消耗 {{points?.pointsSpent??'—'}} 积分，不计入现金销售</small></article></div>
<el-alert v-if="summaryErrors.length" :title="'部分统计加载失败：'+summaryErrors.join('、')" type="warning" :closable="false"/>
<div class="df-card"><el-tabs v-model="tab" @tab-change="change"><el-tab-pane v-for="m in modules" :key="m.key" :name="m.key" :label="m.label"/></el-tabs><div class="commerce-filter"><el-select v-model="status" clearable placeholder="全部状态" style="width:190px" @change="page=1;load()"><el-option v-for="key in states" :key="key" :label="labels[key]" :value="key"/></el-select><span>{{total===null?'每页 20 条':'共 '+total+' 条'}}</span></div><el-alert v-if="error" :title="error" type="error" :closable="false"/>
<el-table :data="rows" v-loading="busy" empty-text="暂无符合条件的记录"><el-table-column label="编号 / 名称" min-width="240"><template #default="{row}"><strong>{{row.name||row.productName||row.orderNo||row.returnNo}}</strong><div class="muted">{{row.orderNo||row.returnNo||'ID '+row.id}}</div></template></el-table-column><el-table-column label="金额 / 积分" min-width="130"><template #default="{row}">{{tab==='points'?row.pointsTotal+' 积分':row.payAmount!=null?'¥'+Number(row.payAmount).toFixed(2):row.totalFee!=null?'¥'+Number(row.totalFee).toFixed(2):row.refundAmount!=null?'¥'+Number(row.refundAmount).toFixed(2):row.price!=null?'¥'+Number(row.price).toFixed(2):'—'}}</template></el-table-column><el-table-column label="库存 / 用户" min-width="110"><template #default="{row}">{{row.stock??row.userId??'—'}}</template></el-table-column><el-table-column label="状态" min-width="130"><template #default="{row}"><el-tag effect="plain">{{labels[row.status]||row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="110" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open(row)">查看详情</el-button></template></el-table-column></el-table><div class="commerce-filter"><el-button :disabled="busy||page===1" @click="page--;load()">上一页</el-button><span>第 {{page}} 页</span><el-button :disabled="busy||(total!==null?page*20>=total:rows.length<20)" @click="page++;load()">下一页</el-button></div></div>
<el-drawer :model-value="!!detail" title="业务详情" size="min(640px, 96vw)" @close="detail=null"><template v-if="detail"><h2>{{detail.name||detail.productName||detail.orderNo||detail.returnNo}}</h2><el-tag>{{labels[detail.status]||detail.status}}</el-tag><el-descriptions :column="1" border style="margin-top:20px"><el-descriptions-item v-for="field in [['id','编号'],['userId','用户'],['description','商品说明'],['reason','售后原因'],['receiver','收货人'],['mobile','手机'],['address','地址'],['carrier','物流公司'],['trackingNo','运单号'],['reviewNote','审核说明']].filter(field=>detail?.[field[0]]!==undefined && detail?.[field[0]]!=='')" :key="field[0]" :label="field[1]">{{detail[field[0]]||'—'}}</el-descriptions-item></el-descriptions><el-table v-if="detail.items" :data="detail.items"><el-table-column label="商品 / 材料"><template #default="{row}">{{row.productName||row.materialName}}</template></el-table-column><el-table-column prop="quantity" label="数量"/></el-table><p v-if="detail.logistics">物流：{{detail.logistics.expressCompany}} {{detail.logistics.trackingNo}}</p><el-button v-if="(detailTab==='orders'&&detail.status==='paid')||(detailTab==='points'&&detail.status==='pending')||(detailTab==='diy'&&detail.status==='awaiting_shipment')" type="primary" :loading="busy" style="margin-top:20px" @click="ship">安排发货</el-button></template></el-drawer>
</template></div></template>
<style scoped>.commerce-supervisor{padding:24px}.commerce-supervisor h2{overflow-wrap:anywhere}@media(max-width:700px){.commerce-supervisor{padding:12px}}.commerce-banner{padding:28px 32px;background:linear-gradient(120deg,#35231c,#795039);color:#f7eee4;border-radius:18px;margin-bottom:22px}.commerce-banner span{color:#e2bd8d;font-size:11px;letter-spacing:3px}.commerce-banner h2{font-size:26px;margin:14px 0}.commerce-banner p{color:#ddc8b3;font-size:13px}.commerce-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:20px 0}.commerce-stats article{background:var(--bg-card,#fff);border:1px solid var(--border,#e8e0d8);border-radius:16px;padding:22px}.commerce-stats span,.commerce-stats small{display:block;color:#8b7b6a;font-size:12px}.commerce-stats b{display:block;font-size:28px;margin:12px 0;color:#9f4933}.commerce-filter{display:flex;gap:14px;align-items:center;margin:16px 0;flex-wrap:wrap}.muted{color:#9a8a7a;font-size:12px;margin-top:4px}@media(max-width:900px){.commerce-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.commerce-banner{padding:22px}.commerce-banner h2{font-size:22px}}</style>
