<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessageBox,ElMessage} from 'element-plus'
import {useAuthStore} from '@/stores/auth'
import client from '@/api/client'
const auth=useAuthStore(),rows=ref<any[]>([]),selected=ref<any>(),history=ref<any[]>([]),status=ref('submitted'),page=ref(1),busy=ref(false),note=ref(''),error=ref('')
const states:Record<string,string>={draft:'草稿',submitted:'待审核',rejected:'已退回',approved:'已通过'}
async function load(){error.value='';try{rows.value=(await client.get<{list:any[]}>(`/auth/onboarding/reviews?status=${status.value}&page=${page.value}`)).list}catch(e){error.value=(e as Error).message}}
async function select(row:any){selected.value=row;note.value='';try{history.value=(await client.get<{list:any[]}>('/auth/onboarding/history?id='+row.id)).list}catch(e){error.value=(e as Error).message}}
async function review(approve:boolean){if(!approve&&!note.value.trim()){error.value='请填写退回原因';return}try{await ElMessageBox.confirm(approve?'确认资料及授权有效？通过后将开通对应业务身份。':'确认退回，申请人可补充材料后重新提交。','审核确认');busy.value=true;await client.post('/auth/onboarding/review',{id:selected.value.id,revision:selected.value.revision,approve,note:note.value});ElMessage.success('审核结果已保存');selected.value=undefined;await load()}catch(e){if(e!=='cancel'&&e!=='close')error.value=e instanceof Error?e.message:'操作未完成'}finally{busy.value=false}}
async function download(id:string){try{const r=await fetch('/api/v1/auth/onboarding/evidence?id='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+auth.token}});if(!r.ok||r.headers.get('content-type')?.includes('json'))throw new Error('无权读取材料');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='认证材料';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){error.value=(e as Error).message}}
onMounted(load)
</script>
<template><div class="df-page"><h1>认证与入驻审核</h1><p>独立大师认证、寺院机构入驻；寺院纳管大师继续由所属寺院管理。</p><p v-if="error" role="alert">{{error}}</p><div class="df-card" style="padding:20px"><el-select v-model="status" @change="page=1;load()"><el-option v-for="(label,value) in states" :key="value" :label="label" :value="value"/></el-select><el-button @click="load">刷新</el-button><el-table :data="rows" @row-click="select"><el-table-column label="申请类型"><template #default="{row}">{{row.kind==='master'?'独立大师':'寺院入驻'}}</template></el-table-column><el-table-column prop="profile.name" label="名称"/><el-table-column label="状态"><template #default="{row}">{{states[row.status]}}</template></el-table-column><el-table-column prop="updatedAt" label="更新时间"/><el-table-column label="操作"><template #default="{row}"><el-button @click.stop="select(row)">查看材料</el-button></template></el-table-column></el-table><el-button :disabled="page<=1" @click="page--;load()">上一页</el-button><el-button :disabled="rows.length<50" @click="page++;load()">下一页</el-button></div>
<el-dialog :model-value="!!selected" title="申请资料" width="min(720px,94vw)" @close="selected=undefined"><template v-if="selected"><el-descriptions :column="1" border><el-descriptions-item v-for="(label,key) in {name:'名称',legalName:'本人／经办人',contact:'联系方式',region:'地区',address:'地址',belief:'流派',sect:'宗派',position:'职务',registrationNumber:'登记证号',description:'介绍'}" :key="key" :label="label">{{key==='belief'?({han_buddhism:'汉传佛教',tibetan_buddhism:'藏传佛教',taoism:'道教',folk:'民间信仰'} as Record<string,string>)[selected.profile[key]]||'—':selected.profile[key]||'—'}}</el-descriptions-item></el-descriptions><p><el-button v-for="(id,i) in selected.profile.evidenceIds" :key="id" @click="download(id)">查看证明 {{Number(i)+1}}</el-button></p><p v-for="(event,i) in history" :key="i">{{event.at}} · {{({save:'保存草稿',submit:'提交审核',approved:'审核通过',rejected:'退回补充'} as Record<string,string>)[event.action]||event.action}} · {{event.note}}</p><template v-if="selected.status==='submitted'"><el-input v-model="note" type="textarea" maxlength="1000" placeholder="审核说明；退回时必填"/><p><el-button :disabled="busy" @click="review(false)">退回补充</el-button><el-button type="primary" :disabled="busy" @click="review(true)">审核通过</el-button></p></template><p v-else>审核意见：{{selected.reviewNote||'无'}}</p></template></el-dialog></div></template>
